/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

public class fuse_entry_out : IDisposable, BufferWritable {
  private IntPtr swigCPtr;
  protected bool swigCMemOwn;

  internal fuse_entry_out(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  internal static IntPtr getCPtr(fuse_entry_out obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  ~fuse_entry_out() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      FuseWrapperPINVOKE.delete_fuse_entry_out(swigCPtr);
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
  }

  public ulong nodeid {
    set {
      FuseWrapperPINVOKE.set_fuse_entry_out_nodeid(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_entry_out_nodeid(swigCPtr);
    } 
  }

  public ulong generation {
    set {
      FuseWrapperPINVOKE.set_fuse_entry_out_generation(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_entry_out_generation(swigCPtr);
    } 
  }

  public ulong entry_valid {
    set {
      FuseWrapperPINVOKE.set_fuse_entry_out_entry_valid(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_entry_out_entry_valid(swigCPtr);
    } 
  }

  public ulong attr_valid {
    set {
      FuseWrapperPINVOKE.set_fuse_entry_out_attr_valid(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_entry_out_attr_valid(swigCPtr);
    } 
  }

  public uint entry_valid_nsec {
    set {
      FuseWrapperPINVOKE.set_fuse_entry_out_entry_valid_nsec(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_entry_out_entry_valid_nsec(swigCPtr);
    } 
  }

  public uint attr_valid_nsec {
    set {
      FuseWrapperPINVOKE.set_fuse_entry_out_attr_valid_nsec(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_entry_out_attr_valid_nsec(swigCPtr);
    } 
  }

  public fuse_attr attr {
    set {
      FuseWrapperPINVOKE.set_fuse_entry_out_attr(swigCPtr, fuse_attr.getCPtr(value));
    } 
    get {
      IntPtr cPtr = FuseWrapperPINVOKE.get_fuse_entry_out_attr(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new fuse_attr(cPtr, false);
    } 
  }

  public int copyTo(FWBuffer buf) {
    return FuseWrapperPINVOKE.fuse_entry_out_copyTo(swigCPtr, FWBuffer.getCPtr(buf));
  }

  public fuse_entry_out() : this(FuseWrapperPINVOKE.new_fuse_entry_out(), true) {
  }

}
