/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

public class fuse_out_header : IDisposable, BufferWritable {
  private IntPtr swigCPtr;
  protected bool swigCMemOwn;

  internal fuse_out_header(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  internal static IntPtr getCPtr(fuse_out_header obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  ~fuse_out_header() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      FuseWrapperPINVOKE.delete_fuse_out_header(swigCPtr);
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
  }

  public uint len {
    set {
      FuseWrapperPINVOKE.set_fuse_out_header_len(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_out_header_len(swigCPtr);
    } 
  }

  public int error {
    set {
      FuseWrapperPINVOKE.set_fuse_out_header_error(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_out_header_error(swigCPtr);
    } 
  }

  public ulong unique {
    set {
      FuseWrapperPINVOKE.set_fuse_out_header_unique(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_out_header_unique(swigCPtr);
    } 
  }

  public int copyTo(FWBuffer buf) {
    return FuseWrapperPINVOKE.fuse_out_header_copyTo(swigCPtr, FWBuffer.getCPtr(buf));
  }

  public fuse_out_header() : this(FuseWrapperPINVOKE.new_fuse_out_header(), true) {
  }

}
