/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

public class fuse_open_out : IDisposable, BufferWritable {
  private IntPtr swigCPtr;
  protected bool swigCMemOwn;

  internal fuse_open_out(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  internal static IntPtr getCPtr(fuse_open_out obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  ~fuse_open_out() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      FuseWrapperPINVOKE.delete_fuse_open_out(swigCPtr);
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
  }

  public ulong fh {
    set {
      FuseWrapperPINVOKE.set_fuse_open_out_fh(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_open_out_fh(swigCPtr);
    } 
  }

  public uint open_flags {
    set {
      FuseWrapperPINVOKE.set_fuse_open_out_open_flags(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_open_out_open_flags(swigCPtr);
    } 
  }

  public uint padding {
    set {
      FuseWrapperPINVOKE.set_fuse_open_out_padding(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_open_out_padding(swigCPtr);
    } 
  }

  public int copyTo(FWBuffer buf) {
    return FuseWrapperPINVOKE.fuse_open_out_copyTo(swigCPtr, FWBuffer.getCPtr(buf));
  }

  public fuse_open_out() : this(FuseWrapperPINVOKE.new_fuse_open_out(), true) {
  }

}
