/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

public class fuse_in_header : IDisposable, BufferReadable {
  private IntPtr swigCPtr;
  protected bool swigCMemOwn;

  internal fuse_in_header(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  internal static IntPtr getCPtr(fuse_in_header obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  ~fuse_in_header() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      FuseWrapperPINVOKE.delete_fuse_in_header(swigCPtr);
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
  }

  public uint len {
    set {
      FuseWrapperPINVOKE.set_fuse_in_header_len(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_in_header_len(swigCPtr);
    } 
  }

  public uint opcode {
    set {
      FuseWrapperPINVOKE.set_fuse_in_header_opcode(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_in_header_opcode(swigCPtr);
    } 
  }

  public ulong unique {
    set {
      FuseWrapperPINVOKE.set_fuse_in_header_unique(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_in_header_unique(swigCPtr);
    } 
  }

  public ulong nodeid {
    set {
      FuseWrapperPINVOKE.set_fuse_in_header_nodeid(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_in_header_nodeid(swigCPtr);
    } 
  }

  public uint uid {
    set {
      FuseWrapperPINVOKE.set_fuse_in_header_uid(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_in_header_uid(swigCPtr);
    } 
  }

  public uint gid {
    set {
      FuseWrapperPINVOKE.set_fuse_in_header_gid(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_in_header_gid(swigCPtr);
    } 
  }

  public uint pid {
    set {
      FuseWrapperPINVOKE.set_fuse_in_header_pid(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_in_header_pid(swigCPtr);
    } 
  }

  public uint padding {
    set {
      FuseWrapperPINVOKE.set_fuse_in_header_padding(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_in_header_padding(swigCPtr);
    } 
  }

  public int copyFrom(FWBuffer buf) {
    return FuseWrapperPINVOKE.fuse_in_header_copyFrom(swigCPtr, FWBuffer.getCPtr(buf));
  }

  public static int structSize() {
    return FuseWrapperPINVOKE.fuse_in_header_structSize();
  }

  public fuse_in_header() : this(FuseWrapperPINVOKE.new_fuse_in_header(), true) {
  }

}
