/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */


#ifndef SWIG_TEMPLATE_DISAMBIGUATOR
#  if defined(__SUNPRO_CC) 
#    define SWIG_TEMPLATE_DISAMBIGUATOR template
#  else
#    define SWIG_TEMPLATE_DISAMBIGUATOR 
#  endif
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#if defined(_WIN32) || defined(__CYGWIN32__)
#  define DllExport   __declspec( dllexport )
#  define SWIGSTDCALL __stdcall
#else
#  define DllExport  
#  define SWIGSTDCALL
#endif 


/* Support for throwing C# exceptions from C/C++ */
typedef enum {
  SWIG_CSharpException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpArgumentOutOfRangeException,
  SWIG_CSharpNullReferenceException
} SWIG_CSharpExceptionCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpExceptions_t;

static SWIG_CSharpExceptions_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL },
  { SWIG_CSharpNullReferenceException, NULL } };

static void SWIG_CSharpThrowException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpException].callback;
  if (code >=0 && (size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpExceptions_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}


#ifdef __cplusplus
extern "C" 
#endif
DllExport void SWIGSTDCALL SWIGRegisterExceptionCallbacks_FuseWrapper(SWIG_CSharpExceptionCallback_t systemException,
                                                          SWIG_CSharpExceptionCallback_t outOfMemory, 
                                                          SWIG_CSharpExceptionCallback_t indexOutOfRange, 
                                                          SWIG_CSharpExceptionCallback_t divideByZero, 
                                                          SWIG_CSharpExceptionCallback_t argumentOutOfRange,
                                                          SWIG_CSharpExceptionCallback_t nullReference) {
  SWIG_csharp_exceptions[SWIG_CSharpException].callback = systemException;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemory;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRange;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZero;
  SWIG_csharp_exceptions[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRange;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReference;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
DllExport void SWIGSTDCALL SWIGRegisterStringCallback_FuseWrapper(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}

/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpThrowException(SWIG_CSharpArgumentOutOfRangeException, msg); return nullreturn; } else


#include "fuse-2.3.h"
#include "FWBuffer.h"
#include <unistd.h>
#include <errno.h>

/* forward definition to silence compiler */
static int FWBuffer_GetBytes( struct FWBuffer *, char *, int );
static int FWBuffer_AddBytes( struct FWBuffer *, char const *, int );

int close_fd( int fd )
{
    return close(fd);
}

#define READSTRUCT(BUF,TYPE) \
return FWBuffer_GetBytes( BUF, (char *)self, sizeof(struct TYPE) );

#define WRITESTRUCT(BUF,TYPE) \
return FWBuffer_AddBytes( BUF, (char const *)self, sizeof(struct TYPE) ); 


static int fuse_entry_out_copyTo(struct fuse_entry_out *self,struct FWBuffer *buf){ WRITESTRUCT( buf, fuse_entry_out ) }
static int fuse_forget_in_copyFrom(struct fuse_forget_in *self,struct FWBuffer *buf){ READSTRUCT( buf, fuse_forget_in ) }
static int fuse_attr_out_copyTo(struct fuse_attr_out *self,struct FWBuffer *buf){ WRITESTRUCT( buf, fuse_attr_out ) }
static int fuse_mknod_in_copyFrom(struct fuse_mknod_in *self,struct FWBuffer *buf){ READSTRUCT( buf, fuse_mknod_in ) }
static int fuse_mkdir_in_copyFrom(struct fuse_mkdir_in *self,struct FWBuffer *buf){ READSTRUCT( buf, fuse_mkdir_in ) }
static int fuse_rename_in_copyFrom(struct fuse_rename_in *self,struct FWBuffer *buf){ READSTRUCT( buf, fuse_rename_in ) }
static int fuse_link_in_copyFrom(struct fuse_link_in *self,struct FWBuffer *buf){ READSTRUCT( buf, fuse_link_in ) }
static int fuse_setattr_in_copyFrom(struct fuse_setattr_in *self,struct FWBuffer *buf){ READSTRUCT( buf, fuse_setattr_in ) }
static int fuse_open_in_copyFrom(struct fuse_open_in *self,struct FWBuffer *buf){ READSTRUCT( buf, fuse_open_in ) }
static int fuse_open_out_copyTo(struct fuse_open_out *self,struct FWBuffer *buf){ WRITESTRUCT( buf, fuse_open_out ) }
static int fuse_release_in_copyFrom(struct fuse_release_in *self,struct FWBuffer *buf){ READSTRUCT( buf, fuse_release_in ) }
static int fuse_flush_in_copyFrom(struct fuse_flush_in *self,struct FWBuffer *buf){ READSTRUCT( buf, fuse_flush_in ) }
static int fuse_read_in_copyFrom(struct fuse_read_in *self,struct FWBuffer *buf){ READSTRUCT( buf, fuse_read_in ) }
static int fuse_write_in_copyFrom(struct fuse_write_in *self,struct FWBuffer *buf){ READSTRUCT( buf, fuse_write_in ) }
static int fuse_write_out_copyTo(struct fuse_write_out *self,struct FWBuffer *buf){ WRITESTRUCT( buf, fuse_write_out ) }
static int fuse_statfs_out_copyTo(struct fuse_statfs_out *self,struct FWBuffer *buf){ WRITESTRUCT( buf, fuse_statfs_out ) }
static int fuse_fsync_in_copyFrom(struct fuse_fsync_in *self,struct FWBuffer *buf){ READSTRUCT( buf, fuse_fsync_in ) }
static int fuse_setxattr_in_copyFrom(struct fuse_setxattr_in *self,struct FWBuffer *buf){ READSTRUCT( buf, fuse_setxattr_in ) }
static int fuse_getxattr_in_copyFrom(struct fuse_getxattr_in *self,struct FWBuffer *buf){ READSTRUCT( buf, fuse_getxattr_in ) }
static int fuse_getxattr_out_copyTo(struct fuse_getxattr_out *self,struct FWBuffer *buf){ WRITESTRUCT( buf, fuse_getxattr_out ) }
static int fuse_init_in_out_copyFrom(struct fuse_init_in_out *self,struct FWBuffer *buf){ READSTRUCT( buf, fuse_init_in_out ) }
static int fuse_init_in_out_copyTo(struct fuse_init_in_out *self,struct FWBuffer *buf){ WRITESTRUCT( buf, fuse_init_in_out ) }
static int fuse_in_header_copyFrom(struct fuse_in_header *self,struct FWBuffer *buf){ READSTRUCT( buf, fuse_in_header ) }
static int fuse_in_header_structSize(){ return sizeof( struct fuse_in_header ); }
static int fuse_out_header_copyTo(struct fuse_out_header *self,struct FWBuffer *buf){ WRITESTRUCT( buf, fuse_out_header ) }
static struct FWBuffer *new_FWBuffer(int size){
	struct FWBuffer *buf = malloc(sizeof(struct FWBuffer));
	buf->data = malloc(size);
	buf->initialized = 0;
	buf->length = size;
	buf->offset = 0;
	return buf;
    }
static void delete_FWBuffer(struct FWBuffer *self){
	self->initialized = 0;
	self->length = 0;
	self->offset = 0;
	free(self->data);
	self->data = 0;
	free(self);
	self = 0;
    }
static void FWBuffer_Rewind(struct FWBuffer *self){
	self->offset = 0;
    }
static void FWBuffer_Reset(struct FWBuffer *self){
	self->initialized = 0;
	self->offset = 0;
	memset(self->data, 0, self->length);
    }
static int FWBuffer_EnsureFreeSpace(struct FWBuffer *self,int freeBytes){
	if( freeBytes + self->offset > self->length )
	{
	    int newSize = 2 * self->length;
	    void *ptr;
	    if(freeBytes + self->offset > newSize)
		newSize = freeBytes + self->offset;
	    ptr = realloc( self->data, newSize );
	    if(ptr == NULL)
		return -ENOMEM;
	    self->data = ptr;
	    self->length = newSize;
	}

    	return 0;
    }
static int FWBuffer_Read__SWIG_0(struct FWBuffer *self,int fd){
	int result = read( fd, self->data + self->offset, 
		self->length - self->offset );
	if(result < 0)
	    result = -errno;
	else
	    self->initialized += result;

	return result;
    }
static int FWBuffer_Read__SWIG_1(struct FWBuffer *self,int fd,size_t count,__u64 offset){
	int result;
	FWBuffer_EnsureFreeSpace( self, count );
	result = pread( fd, self->data + self->offset, count, offset );
	if(result < 0)
	    result = -errno;
	else
	    self->initialized += result;

	return result;
    }
static int FWBuffer_Write__SWIG_0(struct FWBuffer *self,int fd,size_t count,__u64 offset){
	int result;
	if(self->offset + count > self->initialized)
	    return -EIO;

	result = pwrite( fd, self->data + self->offset, count, offset );
	if(result < 0)
	    result = -errno;
	else
	    self->offset += result;

	return result;
    }
static int FWBuffer_Write__SWIG_1(struct FWBuffer *self,int fd){
	int result = write( fd, self->data + self->offset, 
		self->initialized - self->offset );
	if(result < 0)
	    result = -errno;
	else
	    self->offset += result;

	return result;
    }
static char const *FWBuffer_GetString(struct FWBuffer *self){
	const char *result = (char*)self->data + self->offset;
	int len = strlen(result);
	if(len + self->offset > self->initialized )
	    return NULL;
	else
	{
	    self->offset += len + 1;
	    return strdup(result);
	}
    }
static int FWBuffer_GetBytes(struct FWBuffer *self,char *data,int len){
	if( self->initialized - self->offset >= len )
	{
	    memcpy( data, self->data + self->offset, len );
	    self->offset += len;
	    return len;
	} else
	    return -1;
    }
static int FWBuffer_GetByte(struct FWBuffer *self){
	if( self->initialized > self->offset )
	{
	    int res = (int)*((unsigned char*)self->data + self->offset);
	    ++self->offset;
	    return res;
	} else
	    return -1;
    }
static int FWBuffer_AddBytes(struct FWBuffer *self,char const *data,int len){
	int res = FWBuffer_EnsureFreeSpace( self, len );
	if(res == 0)
	{
	    memcpy( self->data + self->offset, data, len );
	    self->offset += len;
	    if(self->initialized < self->offset)
		self->initialized = self->offset;
	    res = len;
	}
	return res;
    }
static int FWBuffer_AddChar(struct FWBuffer *self,int len,char value){
	int res = FWBuffer_EnsureFreeSpace( self, len );
	if(res == 0)
	{
	    memset( self->data + self->offset, value, len );
	    self->offset += len;
	    if(self->initialized < self->offset)
		self->initialized = self->offset;
	}
	return res;
    }
static int FWBuffer_AddString(struct FWBuffer *self,char const *str){
	int len = strlen( str ) + 1;
	return FWBuffer_AddBytes( self, str, len );
    }
static int FWBuffer_AddSubString(struct FWBuffer *self,char const *str,int offset,int len){
	return FWBuffer_AddBytes( self, str+offset, len );
    }
static int FWBuffer_AddBuffer(struct FWBuffer *self,struct FWBuffer *arg){
	return FWBuffer_AddBytes( self, 
		arg->data + arg->offset, arg->initialized - arg->offset);
    }
static int FWBuffer_copyTo(struct FWBuffer *self,struct FWBuffer *outBuf){
	return FWBuffer_AddBytes( outBuf, 
		self->data + self->offset, self->initialized - self->offset);
    }
static struct FileBuffer *new_FileBuffer(struct FWBuffer *buffer){
	struct FileBuffer *buf = malloc(sizeof(struct FileBuffer));
	buf->buf = buffer;
	buf->error = 0;
	return buf;
    }
static void delete_FileBuffer(struct FileBuffer *self){
	free( self );
    }
static int FileBuffer_addFile(struct FileBuffer *self,char const *name,__u64 nodeId,__u32 type,__u64 off){
	// make sure buffer has enough space
	unsigned namelen = strlen( name );
	unsigned entlen;
	unsigned entsize;
	unsigned newlen;
	unsigned padlen;
	struct fuse_dirent dirent;

	if(namelen > 1024)
	    namelen = 1024;
	else if (!namelen)
	{
	    self->error = -EIO;
	    return 1;
	}

	entlen = ((unsigned) ((struct fuse_dirent *) 0)->name) + namelen;
	entsize = (((entlen) + sizeof(__u64) - 1) & ~(sizeof(__u64) - 1));
	padlen = entsize - entlen;
	newlen = self->buf->offset + entsize;
	//if(off && newlen > self->reqLen ) return 1;

	// TODO: allow inode number passthru
	dirent.ino = -1;
	dirent.off = off ? off : newlen;
	dirent.namelen = namelen;
	dirent.type = type;

	FWBuffer_AddBytes( self->buf, (char*)&dirent, 
		sizeof(struct fuse_dirent));
	FWBuffer_AddBytes( self->buf, name, namelen );
	if(padlen)
	    FWBuffer_AddChar( self->buf, padlen, '\0' );

	return 0;
    }
static int FileBuffer_copyTo(struct FileBuffer *self,struct FWBuffer *outBuf){
	int res;
	int off = self->buf->offset;
	FWBuffer_Rewind( self->buf );
	res = FWBuffer_copyTo( self->buf, outBuf );
	self->buf->offset = off;
	return res;
    }

#ifdef __cplusplus
extern "C" {
#endif

DllExport int SWIGSTDCALL CSharp_get__FILE_OFFSET_BITS() {
    int jresult = 0 ;
    int result;
    
    result = (int) 64;
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_close_fd(int jarg1) {
    int jresult = 0 ;
    int arg1 ;
    int result;
    
    arg1 = (int)jarg1; 
    result = (int)close_fd(arg1);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_attr_ino(void * jarg1, unsigned long long jarg2) {
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned long long arg2 ;
    
    arg1 = (struct fuse_attr *)jarg1; 
    arg2 = (unsigned long long)jarg2; 
    if (arg1) (arg1)->ino = arg2;
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_attr_ino(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_attr *)jarg1; 
    result = (unsigned long long) ((arg1)->ino);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_attr_size(void * jarg1, unsigned long long jarg2) {
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned long long arg2 ;
    
    arg1 = (struct fuse_attr *)jarg1; 
    arg2 = (unsigned long long)jarg2; 
    if (arg1) (arg1)->size = arg2;
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_attr_size(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_attr *)jarg1; 
    result = (unsigned long long) ((arg1)->size);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_attr_blocks(void * jarg1, unsigned long long jarg2) {
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned long long arg2 ;
    
    arg1 = (struct fuse_attr *)jarg1; 
    arg2 = (unsigned long long)jarg2; 
    if (arg1) (arg1)->blocks = arg2;
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_attr_blocks(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_attr *)jarg1; 
    result = (unsigned long long) ((arg1)->blocks);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_attr_atime(void * jarg1, unsigned long long jarg2) {
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned long long arg2 ;
    
    arg1 = (struct fuse_attr *)jarg1; 
    arg2 = (unsigned long long)jarg2; 
    if (arg1) (arg1)->atime = arg2;
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_attr_atime(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_attr *)jarg1; 
    result = (unsigned long long) ((arg1)->atime);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_attr_mtime(void * jarg1, unsigned long long jarg2) {
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned long long arg2 ;
    
    arg1 = (struct fuse_attr *)jarg1; 
    arg2 = (unsigned long long)jarg2; 
    if (arg1) (arg1)->mtime = arg2;
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_attr_mtime(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_attr *)jarg1; 
    result = (unsigned long long) ((arg1)->mtime);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_attr_ctime(void * jarg1, unsigned long long jarg2) {
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned long long arg2 ;
    
    arg1 = (struct fuse_attr *)jarg1; 
    arg2 = (unsigned long long)jarg2; 
    if (arg1) (arg1)->ctime = arg2;
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_attr_ctime(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_attr *)jarg1; 
    result = (unsigned long long) ((arg1)->ctime);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_attr_atimensec(void * jarg1, unsigned int jarg2) {
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_attr *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->atimensec = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_attr_atimensec(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_attr *)jarg1; 
    result = (unsigned int) ((arg1)->atimensec);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_attr_mtimensec(void * jarg1, unsigned int jarg2) {
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_attr *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->mtimensec = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_attr_mtimensec(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_attr *)jarg1; 
    result = (unsigned int) ((arg1)->mtimensec);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_attr_ctimensec(void * jarg1, unsigned int jarg2) {
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_attr *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->ctimensec = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_attr_ctimensec(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_attr *)jarg1; 
    result = (unsigned int) ((arg1)->ctimensec);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_attr_mode(void * jarg1, unsigned int jarg2) {
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_attr *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->mode = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_attr_mode(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_attr *)jarg1; 
    result = (unsigned int) ((arg1)->mode);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_attr_nlink(void * jarg1, unsigned int jarg2) {
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_attr *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->nlink = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_attr_nlink(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_attr *)jarg1; 
    result = (unsigned int) ((arg1)->nlink);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_attr_uid(void * jarg1, unsigned int jarg2) {
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_attr *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->uid = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_attr_uid(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_attr *)jarg1; 
    result = (unsigned int) ((arg1)->uid);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_attr_gid(void * jarg1, unsigned int jarg2) {
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_attr *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->gid = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_attr_gid(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_attr *)jarg1; 
    result = (unsigned int) ((arg1)->gid);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_attr_rdev(void * jarg1, unsigned int jarg2) {
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_attr *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->rdev = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_attr_rdev(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_attr *)jarg1; 
    result = (unsigned int) ((arg1)->rdev);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_fuse_attr() {
    void * jresult = 0 ;
    struct fuse_attr *result;
    
    result = (struct fuse_attr *)(struct fuse_attr *) calloc(1, sizeof(struct fuse_attr));
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_fuse_attr(void * jarg1) {
    struct fuse_attr *arg1 = (struct fuse_attr *) 0 ;
    
    arg1 = (struct fuse_attr *)jarg1; 
    free((char *) arg1);
    
}


DllExport void SWIGSTDCALL CSharp_set_fuse_kstatfs_blocks(void * jarg1, unsigned long long jarg2) {
    struct fuse_kstatfs *arg1 = (struct fuse_kstatfs *) 0 ;
    unsigned long long arg2 ;
    
    arg1 = (struct fuse_kstatfs *)jarg1; 
    arg2 = (unsigned long long)jarg2; 
    if (arg1) (arg1)->blocks = arg2;
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_kstatfs_blocks(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_kstatfs *arg1 = (struct fuse_kstatfs *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_kstatfs *)jarg1; 
    result = (unsigned long long) ((arg1)->blocks);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_kstatfs_bfree(void * jarg1, unsigned long long jarg2) {
    struct fuse_kstatfs *arg1 = (struct fuse_kstatfs *) 0 ;
    unsigned long long arg2 ;
    
    arg1 = (struct fuse_kstatfs *)jarg1; 
    arg2 = (unsigned long long)jarg2; 
    if (arg1) (arg1)->bfree = arg2;
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_kstatfs_bfree(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_kstatfs *arg1 = (struct fuse_kstatfs *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_kstatfs *)jarg1; 
    result = (unsigned long long) ((arg1)->bfree);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_kstatfs_bavail(void * jarg1, unsigned long long jarg2) {
    struct fuse_kstatfs *arg1 = (struct fuse_kstatfs *) 0 ;
    unsigned long long arg2 ;
    
    arg1 = (struct fuse_kstatfs *)jarg1; 
    arg2 = (unsigned long long)jarg2; 
    if (arg1) (arg1)->bavail = arg2;
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_kstatfs_bavail(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_kstatfs *arg1 = (struct fuse_kstatfs *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_kstatfs *)jarg1; 
    result = (unsigned long long) ((arg1)->bavail);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_kstatfs_files(void * jarg1, unsigned long long jarg2) {
    struct fuse_kstatfs *arg1 = (struct fuse_kstatfs *) 0 ;
    unsigned long long arg2 ;
    
    arg1 = (struct fuse_kstatfs *)jarg1; 
    arg2 = (unsigned long long)jarg2; 
    if (arg1) (arg1)->files = arg2;
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_kstatfs_files(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_kstatfs *arg1 = (struct fuse_kstatfs *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_kstatfs *)jarg1; 
    result = (unsigned long long) ((arg1)->files);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_kstatfs_ffree(void * jarg1, unsigned long long jarg2) {
    struct fuse_kstatfs *arg1 = (struct fuse_kstatfs *) 0 ;
    unsigned long long arg2 ;
    
    arg1 = (struct fuse_kstatfs *)jarg1; 
    arg2 = (unsigned long long)jarg2; 
    if (arg1) (arg1)->ffree = arg2;
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_kstatfs_ffree(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_kstatfs *arg1 = (struct fuse_kstatfs *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_kstatfs *)jarg1; 
    result = (unsigned long long) ((arg1)->ffree);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_kstatfs_bsize(void * jarg1, unsigned int jarg2) {
    struct fuse_kstatfs *arg1 = (struct fuse_kstatfs *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_kstatfs *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->bsize = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_kstatfs_bsize(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_kstatfs *arg1 = (struct fuse_kstatfs *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_kstatfs *)jarg1; 
    result = (unsigned int) ((arg1)->bsize);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_kstatfs_namelen(void * jarg1, unsigned int jarg2) {
    struct fuse_kstatfs *arg1 = (struct fuse_kstatfs *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_kstatfs *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->namelen = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_kstatfs_namelen(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_kstatfs *arg1 = (struct fuse_kstatfs *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_kstatfs *)jarg1; 
    result = (unsigned int) ((arg1)->namelen);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_fuse_kstatfs() {
    void * jresult = 0 ;
    struct fuse_kstatfs *result;
    
    result = (struct fuse_kstatfs *)(struct fuse_kstatfs *) calloc(1, sizeof(struct fuse_kstatfs));
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_fuse_kstatfs(void * jarg1) {
    struct fuse_kstatfs *arg1 = (struct fuse_kstatfs *) 0 ;
    
    arg1 = (struct fuse_kstatfs *)jarg1; 
    free((char *) arg1);
    
}


DllExport void SWIGSTDCALL CSharp_set_fuse_entry_out_nodeid(void * jarg1, unsigned long long jarg2) {
    struct fuse_entry_out *arg1 = (struct fuse_entry_out *) 0 ;
    unsigned long long arg2 ;
    
    arg1 = (struct fuse_entry_out *)jarg1; 
    arg2 = (unsigned long long)jarg2; 
    if (arg1) (arg1)->nodeid = arg2;
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_entry_out_nodeid(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_entry_out *arg1 = (struct fuse_entry_out *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_entry_out *)jarg1; 
    result = (unsigned long long) ((arg1)->nodeid);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_entry_out_generation(void * jarg1, unsigned long long jarg2) {
    struct fuse_entry_out *arg1 = (struct fuse_entry_out *) 0 ;
    unsigned long long arg2 ;
    
    arg1 = (struct fuse_entry_out *)jarg1; 
    arg2 = (unsigned long long)jarg2; 
    if (arg1) (arg1)->generation = arg2;
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_entry_out_generation(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_entry_out *arg1 = (struct fuse_entry_out *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_entry_out *)jarg1; 
    result = (unsigned long long) ((arg1)->generation);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_entry_out_entry_valid(void * jarg1, unsigned long long jarg2) {
    struct fuse_entry_out *arg1 = (struct fuse_entry_out *) 0 ;
    unsigned long long arg2 ;
    
    arg1 = (struct fuse_entry_out *)jarg1; 
    arg2 = (unsigned long long)jarg2; 
    if (arg1) (arg1)->entry_valid = arg2;
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_entry_out_entry_valid(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_entry_out *arg1 = (struct fuse_entry_out *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_entry_out *)jarg1; 
    result = (unsigned long long) ((arg1)->entry_valid);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_entry_out_attr_valid(void * jarg1, unsigned long long jarg2) {
    struct fuse_entry_out *arg1 = (struct fuse_entry_out *) 0 ;
    unsigned long long arg2 ;
    
    arg1 = (struct fuse_entry_out *)jarg1; 
    arg2 = (unsigned long long)jarg2; 
    if (arg1) (arg1)->attr_valid = arg2;
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_entry_out_attr_valid(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_entry_out *arg1 = (struct fuse_entry_out *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_entry_out *)jarg1; 
    result = (unsigned long long) ((arg1)->attr_valid);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_entry_out_entry_valid_nsec(void * jarg1, unsigned int jarg2) {
    struct fuse_entry_out *arg1 = (struct fuse_entry_out *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_entry_out *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->entry_valid_nsec = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_entry_out_entry_valid_nsec(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_entry_out *arg1 = (struct fuse_entry_out *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_entry_out *)jarg1; 
    result = (unsigned int) ((arg1)->entry_valid_nsec);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_entry_out_attr_valid_nsec(void * jarg1, unsigned int jarg2) {
    struct fuse_entry_out *arg1 = (struct fuse_entry_out *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_entry_out *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->attr_valid_nsec = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_entry_out_attr_valid_nsec(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_entry_out *arg1 = (struct fuse_entry_out *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_entry_out *)jarg1; 
    result = (unsigned int) ((arg1)->attr_valid_nsec);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_entry_out_attr(void * jarg1, void * jarg2) {
    struct fuse_entry_out *arg1 = (struct fuse_entry_out *) 0 ;
    struct fuse_attr *arg2 = (struct fuse_attr *) 0 ;
    
    arg1 = (struct fuse_entry_out *)jarg1; 
    arg2 = (struct fuse_attr *)jarg2; 
    if (arg1) (arg1)->attr = *arg2;
    
}


DllExport void * SWIGSTDCALL CSharp_get_fuse_entry_out_attr(void * jarg1) {
    void * jresult = 0 ;
    struct fuse_entry_out *arg1 = (struct fuse_entry_out *) 0 ;
    struct fuse_attr *result;
    
    arg1 = (struct fuse_entry_out *)jarg1; 
    result = (struct fuse_attr *)& ((arg1)->attr);
    
    jresult = (void *)result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_fuse_entry_out_copyTo(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct fuse_entry_out *arg1 = (struct fuse_entry_out *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct fuse_entry_out *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)fuse_entry_out_copyTo(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_fuse_entry_out() {
    void * jresult = 0 ;
    struct fuse_entry_out *result;
    
    result = (struct fuse_entry_out *)(struct fuse_entry_out *) calloc(1, sizeof(struct fuse_entry_out));
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_fuse_entry_out(void * jarg1) {
    struct fuse_entry_out *arg1 = (struct fuse_entry_out *) 0 ;
    
    arg1 = (struct fuse_entry_out *)jarg1; 
    free((char *) arg1);
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_forget_in_version(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_forget_in *arg1 = (struct fuse_forget_in *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_forget_in *)jarg1; 
    result = (unsigned long long) ((arg1)->version);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_fuse_forget_in_copyFrom(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct fuse_forget_in *arg1 = (struct fuse_forget_in *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct fuse_forget_in *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)fuse_forget_in_copyFrom(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_fuse_forget_in() {
    void * jresult = 0 ;
    struct fuse_forget_in *result;
    
    result = (struct fuse_forget_in *)(struct fuse_forget_in *) calloc(1, sizeof(struct fuse_forget_in));
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_fuse_forget_in(void * jarg1) {
    struct fuse_forget_in *arg1 = (struct fuse_forget_in *) 0 ;
    
    arg1 = (struct fuse_forget_in *)jarg1; 
    free((char *) arg1);
    
}


DllExport void SWIGSTDCALL CSharp_set_fuse_attr_out_attr_valid(void * jarg1, unsigned long long jarg2) {
    struct fuse_attr_out *arg1 = (struct fuse_attr_out *) 0 ;
    unsigned long long arg2 ;
    
    arg1 = (struct fuse_attr_out *)jarg1; 
    arg2 = (unsigned long long)jarg2; 
    if (arg1) (arg1)->attr_valid = arg2;
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_attr_out_attr_valid(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_attr_out *arg1 = (struct fuse_attr_out *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_attr_out *)jarg1; 
    result = (unsigned long long) ((arg1)->attr_valid);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_attr_out_attr_valid_nsec(void * jarg1, unsigned int jarg2) {
    struct fuse_attr_out *arg1 = (struct fuse_attr_out *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_attr_out *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->attr_valid_nsec = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_attr_out_attr_valid_nsec(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_attr_out *arg1 = (struct fuse_attr_out *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_attr_out *)jarg1; 
    result = (unsigned int) ((arg1)->attr_valid_nsec);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_attr_out_dummy(void * jarg1, unsigned int jarg2) {
    struct fuse_attr_out *arg1 = (struct fuse_attr_out *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_attr_out *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->dummy = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_attr_out_dummy(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_attr_out *arg1 = (struct fuse_attr_out *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_attr_out *)jarg1; 
    result = (unsigned int) ((arg1)->dummy);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_attr_out_attr(void * jarg1, void * jarg2) {
    struct fuse_attr_out *arg1 = (struct fuse_attr_out *) 0 ;
    struct fuse_attr *arg2 = (struct fuse_attr *) 0 ;
    
    arg1 = (struct fuse_attr_out *)jarg1; 
    arg2 = (struct fuse_attr *)jarg2; 
    if (arg1) (arg1)->attr = *arg2;
    
}


DllExport void * SWIGSTDCALL CSharp_get_fuse_attr_out_attr(void * jarg1) {
    void * jresult = 0 ;
    struct fuse_attr_out *arg1 = (struct fuse_attr_out *) 0 ;
    struct fuse_attr *result;
    
    arg1 = (struct fuse_attr_out *)jarg1; 
    result = (struct fuse_attr *)& ((arg1)->attr);
    
    jresult = (void *)result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_fuse_attr_out_copyTo(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct fuse_attr_out *arg1 = (struct fuse_attr_out *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct fuse_attr_out *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)fuse_attr_out_copyTo(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_fuse_attr_out() {
    void * jresult = 0 ;
    struct fuse_attr_out *result;
    
    result = (struct fuse_attr_out *)(struct fuse_attr_out *) calloc(1, sizeof(struct fuse_attr_out));
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_fuse_attr_out(void * jarg1) {
    struct fuse_attr_out *arg1 = (struct fuse_attr_out *) 0 ;
    
    arg1 = (struct fuse_attr_out *)jarg1; 
    free((char *) arg1);
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_mknod_in_mode(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_mknod_in *arg1 = (struct fuse_mknod_in *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_mknod_in *)jarg1; 
    result = (unsigned int) ((arg1)->mode);
    
    jresult = result; 
    return jresult;
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_mknod_in_rdev(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_mknod_in *arg1 = (struct fuse_mknod_in *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_mknod_in *)jarg1; 
    result = (unsigned int) ((arg1)->rdev);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_fuse_mknod_in_copyFrom(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct fuse_mknod_in *arg1 = (struct fuse_mknod_in *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct fuse_mknod_in *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)fuse_mknod_in_copyFrom(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_fuse_mknod_in() {
    void * jresult = 0 ;
    struct fuse_mknod_in *result;
    
    result = (struct fuse_mknod_in *)(struct fuse_mknod_in *) calloc(1, sizeof(struct fuse_mknod_in));
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_fuse_mknod_in(void * jarg1) {
    struct fuse_mknod_in *arg1 = (struct fuse_mknod_in *) 0 ;
    
    arg1 = (struct fuse_mknod_in *)jarg1; 
    free((char *) arg1);
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_mkdir_in_mode(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_mkdir_in *arg1 = (struct fuse_mkdir_in *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_mkdir_in *)jarg1; 
    result = (unsigned int) ((arg1)->mode);
    
    jresult = result; 
    return jresult;
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_mkdir_in_padding(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_mkdir_in *arg1 = (struct fuse_mkdir_in *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_mkdir_in *)jarg1; 
    result = (unsigned int) ((arg1)->padding);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_fuse_mkdir_in_copyFrom(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct fuse_mkdir_in *arg1 = (struct fuse_mkdir_in *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct fuse_mkdir_in *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)fuse_mkdir_in_copyFrom(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_fuse_mkdir_in() {
    void * jresult = 0 ;
    struct fuse_mkdir_in *result;
    
    result = (struct fuse_mkdir_in *)(struct fuse_mkdir_in *) calloc(1, sizeof(struct fuse_mkdir_in));
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_fuse_mkdir_in(void * jarg1) {
    struct fuse_mkdir_in *arg1 = (struct fuse_mkdir_in *) 0 ;
    
    arg1 = (struct fuse_mkdir_in *)jarg1; 
    free((char *) arg1);
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_rename_in_newdir(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_rename_in *arg1 = (struct fuse_rename_in *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_rename_in *)jarg1; 
    result = (unsigned long long) ((arg1)->newdir);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_fuse_rename_in_copyFrom(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct fuse_rename_in *arg1 = (struct fuse_rename_in *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct fuse_rename_in *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)fuse_rename_in_copyFrom(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_fuse_rename_in() {
    void * jresult = 0 ;
    struct fuse_rename_in *result;
    
    result = (struct fuse_rename_in *)(struct fuse_rename_in *) calloc(1, sizeof(struct fuse_rename_in));
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_fuse_rename_in(void * jarg1) {
    struct fuse_rename_in *arg1 = (struct fuse_rename_in *) 0 ;
    
    arg1 = (struct fuse_rename_in *)jarg1; 
    free((char *) arg1);
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_link_in_oldnodeid(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_link_in *arg1 = (struct fuse_link_in *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_link_in *)jarg1; 
    result = (unsigned long long) ((arg1)->oldnodeid);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_fuse_link_in_copyFrom(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct fuse_link_in *arg1 = (struct fuse_link_in *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct fuse_link_in *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)fuse_link_in_copyFrom(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_fuse_link_in() {
    void * jresult = 0 ;
    struct fuse_link_in *result;
    
    result = (struct fuse_link_in *)(struct fuse_link_in *) calloc(1, sizeof(struct fuse_link_in));
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_fuse_link_in(void * jarg1) {
    struct fuse_link_in *arg1 = (struct fuse_link_in *) 0 ;
    
    arg1 = (struct fuse_link_in *)jarg1; 
    free((char *) arg1);
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_setattr_in_valid(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_setattr_in *arg1 = (struct fuse_setattr_in *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_setattr_in *)jarg1; 
    result = (unsigned int) ((arg1)->valid);
    
    jresult = result; 
    return jresult;
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_setattr_in_padding(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_setattr_in *arg1 = (struct fuse_setattr_in *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_setattr_in *)jarg1; 
    result = (unsigned int) ((arg1)->padding);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_get_fuse_setattr_in_attr(void * jarg1) {
    void * jresult = 0 ;
    struct fuse_setattr_in *arg1 = (struct fuse_setattr_in *) 0 ;
    struct fuse_attr *result;
    
    arg1 = (struct fuse_setattr_in *)jarg1; 
    result = (struct fuse_attr *)& ((arg1)->attr);
    
    jresult = (void *)result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_fuse_setattr_in_copyFrom(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct fuse_setattr_in *arg1 = (struct fuse_setattr_in *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct fuse_setattr_in *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)fuse_setattr_in_copyFrom(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_fuse_setattr_in() {
    void * jresult = 0 ;
    struct fuse_setattr_in *result;
    
    result = (struct fuse_setattr_in *)(struct fuse_setattr_in *) calloc(1, sizeof(struct fuse_setattr_in));
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_fuse_setattr_in(void * jarg1) {
    struct fuse_setattr_in *arg1 = (struct fuse_setattr_in *) 0 ;
    
    arg1 = (struct fuse_setattr_in *)jarg1; 
    free((char *) arg1);
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_open_in_flags(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_open_in *arg1 = (struct fuse_open_in *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_open_in *)jarg1; 
    result = (unsigned int) ((arg1)->flags);
    
    jresult = result; 
    return jresult;
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_open_in_padding(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_open_in *arg1 = (struct fuse_open_in *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_open_in *)jarg1; 
    result = (unsigned int) ((arg1)->padding);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_fuse_open_in_copyFrom(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct fuse_open_in *arg1 = (struct fuse_open_in *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct fuse_open_in *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)fuse_open_in_copyFrom(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_fuse_open_in() {
    void * jresult = 0 ;
    struct fuse_open_in *result;
    
    result = (struct fuse_open_in *)(struct fuse_open_in *) calloc(1, sizeof(struct fuse_open_in));
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_fuse_open_in(void * jarg1) {
    struct fuse_open_in *arg1 = (struct fuse_open_in *) 0 ;
    
    arg1 = (struct fuse_open_in *)jarg1; 
    free((char *) arg1);
    
}


DllExport void SWIGSTDCALL CSharp_set_fuse_open_out_fh(void * jarg1, unsigned long long jarg2) {
    struct fuse_open_out *arg1 = (struct fuse_open_out *) 0 ;
    unsigned long long arg2 ;
    
    arg1 = (struct fuse_open_out *)jarg1; 
    arg2 = (unsigned long long)jarg2; 
    if (arg1) (arg1)->fh = arg2;
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_open_out_fh(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_open_out *arg1 = (struct fuse_open_out *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_open_out *)jarg1; 
    result = (unsigned long long) ((arg1)->fh);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_open_out_open_flags(void * jarg1, unsigned int jarg2) {
    struct fuse_open_out *arg1 = (struct fuse_open_out *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_open_out *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->open_flags = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_open_out_open_flags(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_open_out *arg1 = (struct fuse_open_out *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_open_out *)jarg1; 
    result = (unsigned int) ((arg1)->open_flags);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_open_out_padding(void * jarg1, unsigned int jarg2) {
    struct fuse_open_out *arg1 = (struct fuse_open_out *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_open_out *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->padding = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_open_out_padding(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_open_out *arg1 = (struct fuse_open_out *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_open_out *)jarg1; 
    result = (unsigned int) ((arg1)->padding);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_fuse_open_out_copyTo(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct fuse_open_out *arg1 = (struct fuse_open_out *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct fuse_open_out *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)fuse_open_out_copyTo(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_fuse_open_out() {
    void * jresult = 0 ;
    struct fuse_open_out *result;
    
    result = (struct fuse_open_out *)(struct fuse_open_out *) calloc(1, sizeof(struct fuse_open_out));
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_fuse_open_out(void * jarg1) {
    struct fuse_open_out *arg1 = (struct fuse_open_out *) 0 ;
    
    arg1 = (struct fuse_open_out *)jarg1; 
    free((char *) arg1);
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_release_in_fh(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_release_in *arg1 = (struct fuse_release_in *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_release_in *)jarg1; 
    result = (unsigned long long) ((arg1)->fh);
    
    jresult = result; 
    return jresult;
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_release_in_flags(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_release_in *arg1 = (struct fuse_release_in *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_release_in *)jarg1; 
    result = (unsigned int) ((arg1)->flags);
    
    jresult = result; 
    return jresult;
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_release_in_padding(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_release_in *arg1 = (struct fuse_release_in *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_release_in *)jarg1; 
    result = (unsigned int) ((arg1)->padding);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_fuse_release_in_copyFrom(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct fuse_release_in *arg1 = (struct fuse_release_in *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct fuse_release_in *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)fuse_release_in_copyFrom(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_fuse_release_in() {
    void * jresult = 0 ;
    struct fuse_release_in *result;
    
    result = (struct fuse_release_in *)(struct fuse_release_in *) calloc(1, sizeof(struct fuse_release_in));
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_fuse_release_in(void * jarg1) {
    struct fuse_release_in *arg1 = (struct fuse_release_in *) 0 ;
    
    arg1 = (struct fuse_release_in *)jarg1; 
    free((char *) arg1);
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_flush_in_fh(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_flush_in *arg1 = (struct fuse_flush_in *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_flush_in *)jarg1; 
    result = (unsigned long long) ((arg1)->fh);
    
    jresult = result; 
    return jresult;
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_flush_in_flush_flags(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_flush_in *arg1 = (struct fuse_flush_in *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_flush_in *)jarg1; 
    result = (unsigned int) ((arg1)->flush_flags);
    
    jresult = result; 
    return jresult;
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_flush_in_padding(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_flush_in *arg1 = (struct fuse_flush_in *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_flush_in *)jarg1; 
    result = (unsigned int) ((arg1)->padding);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_fuse_flush_in_copyFrom(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct fuse_flush_in *arg1 = (struct fuse_flush_in *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct fuse_flush_in *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)fuse_flush_in_copyFrom(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_fuse_flush_in() {
    void * jresult = 0 ;
    struct fuse_flush_in *result;
    
    result = (struct fuse_flush_in *)(struct fuse_flush_in *) calloc(1, sizeof(struct fuse_flush_in));
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_fuse_flush_in(void * jarg1) {
    struct fuse_flush_in *arg1 = (struct fuse_flush_in *) 0 ;
    
    arg1 = (struct fuse_flush_in *)jarg1; 
    free((char *) arg1);
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_read_in_fh(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_read_in *arg1 = (struct fuse_read_in *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_read_in *)jarg1; 
    result = (unsigned long long) ((arg1)->fh);
    
    jresult = result; 
    return jresult;
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_read_in_offset(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_read_in *arg1 = (struct fuse_read_in *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_read_in *)jarg1; 
    result = (unsigned long long) ((arg1)->offset);
    
    jresult = result; 
    return jresult;
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_read_in_size(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_read_in *arg1 = (struct fuse_read_in *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_read_in *)jarg1; 
    result = (unsigned int) ((arg1)->size);
    
    jresult = result; 
    return jresult;
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_read_in_padding(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_read_in *arg1 = (struct fuse_read_in *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_read_in *)jarg1; 
    result = (unsigned int) ((arg1)->padding);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_fuse_read_in_copyFrom(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct fuse_read_in *arg1 = (struct fuse_read_in *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct fuse_read_in *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)fuse_read_in_copyFrom(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_fuse_read_in() {
    void * jresult = 0 ;
    struct fuse_read_in *result;
    
    result = (struct fuse_read_in *)(struct fuse_read_in *) calloc(1, sizeof(struct fuse_read_in));
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_fuse_read_in(void * jarg1) {
    struct fuse_read_in *arg1 = (struct fuse_read_in *) 0 ;
    
    arg1 = (struct fuse_read_in *)jarg1; 
    free((char *) arg1);
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_write_in_fh(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_write_in *arg1 = (struct fuse_write_in *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_write_in *)jarg1; 
    result = (unsigned long long) ((arg1)->fh);
    
    jresult = result; 
    return jresult;
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_write_in_offset(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_write_in *arg1 = (struct fuse_write_in *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_write_in *)jarg1; 
    result = (unsigned long long) ((arg1)->offset);
    
    jresult = result; 
    return jresult;
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_write_in_size(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_write_in *arg1 = (struct fuse_write_in *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_write_in *)jarg1; 
    result = (unsigned int) ((arg1)->size);
    
    jresult = result; 
    return jresult;
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_write_in_write_flags(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_write_in *arg1 = (struct fuse_write_in *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_write_in *)jarg1; 
    result = (unsigned int) ((arg1)->write_flags);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_fuse_write_in_copyFrom(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct fuse_write_in *arg1 = (struct fuse_write_in *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct fuse_write_in *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)fuse_write_in_copyFrom(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_fuse_write_in() {
    void * jresult = 0 ;
    struct fuse_write_in *result;
    
    result = (struct fuse_write_in *)(struct fuse_write_in *) calloc(1, sizeof(struct fuse_write_in));
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_fuse_write_in(void * jarg1) {
    struct fuse_write_in *arg1 = (struct fuse_write_in *) 0 ;
    
    arg1 = (struct fuse_write_in *)jarg1; 
    free((char *) arg1);
    
}


DllExport void SWIGSTDCALL CSharp_set_fuse_write_out_size(void * jarg1, unsigned int jarg2) {
    struct fuse_write_out *arg1 = (struct fuse_write_out *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_write_out *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->size = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_write_out_size(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_write_out *arg1 = (struct fuse_write_out *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_write_out *)jarg1; 
    result = (unsigned int) ((arg1)->size);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_write_out_padding(void * jarg1, unsigned int jarg2) {
    struct fuse_write_out *arg1 = (struct fuse_write_out *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_write_out *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->padding = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_write_out_padding(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_write_out *arg1 = (struct fuse_write_out *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_write_out *)jarg1; 
    result = (unsigned int) ((arg1)->padding);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_fuse_write_out_copyTo(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct fuse_write_out *arg1 = (struct fuse_write_out *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct fuse_write_out *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)fuse_write_out_copyTo(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_fuse_write_out() {
    void * jresult = 0 ;
    struct fuse_write_out *result;
    
    result = (struct fuse_write_out *)(struct fuse_write_out *) calloc(1, sizeof(struct fuse_write_out));
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_fuse_write_out(void * jarg1) {
    struct fuse_write_out *arg1 = (struct fuse_write_out *) 0 ;
    
    arg1 = (struct fuse_write_out *)jarg1; 
    free((char *) arg1);
    
}


DllExport void SWIGSTDCALL CSharp_set_fuse_statfs_out_st(void * jarg1, void * jarg2) {
    struct fuse_statfs_out *arg1 = (struct fuse_statfs_out *) 0 ;
    struct fuse_kstatfs *arg2 = (struct fuse_kstatfs *) 0 ;
    
    arg1 = (struct fuse_statfs_out *)jarg1; 
    arg2 = (struct fuse_kstatfs *)jarg2; 
    if (arg1) (arg1)->st = *arg2;
    
}


DllExport void * SWIGSTDCALL CSharp_get_fuse_statfs_out_st(void * jarg1) {
    void * jresult = 0 ;
    struct fuse_statfs_out *arg1 = (struct fuse_statfs_out *) 0 ;
    struct fuse_kstatfs *result;
    
    arg1 = (struct fuse_statfs_out *)jarg1; 
    result = (struct fuse_kstatfs *)& ((arg1)->st);
    
    jresult = (void *)result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_fuse_statfs_out_copyTo(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct fuse_statfs_out *arg1 = (struct fuse_statfs_out *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct fuse_statfs_out *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)fuse_statfs_out_copyTo(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_fuse_statfs_out() {
    void * jresult = 0 ;
    struct fuse_statfs_out *result;
    
    result = (struct fuse_statfs_out *)(struct fuse_statfs_out *) calloc(1, sizeof(struct fuse_statfs_out));
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_fuse_statfs_out(void * jarg1) {
    struct fuse_statfs_out *arg1 = (struct fuse_statfs_out *) 0 ;
    
    arg1 = (struct fuse_statfs_out *)jarg1; 
    free((char *) arg1);
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_fsync_in_fh(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_fsync_in *arg1 = (struct fuse_fsync_in *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_fsync_in *)jarg1; 
    result = (unsigned long long) ((arg1)->fh);
    
    jresult = result; 
    return jresult;
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_fsync_in_fsync_flags(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_fsync_in *arg1 = (struct fuse_fsync_in *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_fsync_in *)jarg1; 
    result = (unsigned int) ((arg1)->fsync_flags);
    
    jresult = result; 
    return jresult;
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_fsync_in_padding(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_fsync_in *arg1 = (struct fuse_fsync_in *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_fsync_in *)jarg1; 
    result = (unsigned int) ((arg1)->padding);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_fuse_fsync_in_copyFrom(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct fuse_fsync_in *arg1 = (struct fuse_fsync_in *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct fuse_fsync_in *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)fuse_fsync_in_copyFrom(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_fuse_fsync_in() {
    void * jresult = 0 ;
    struct fuse_fsync_in *result;
    
    result = (struct fuse_fsync_in *)(struct fuse_fsync_in *) calloc(1, sizeof(struct fuse_fsync_in));
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_fuse_fsync_in(void * jarg1) {
    struct fuse_fsync_in *arg1 = (struct fuse_fsync_in *) 0 ;
    
    arg1 = (struct fuse_fsync_in *)jarg1; 
    free((char *) arg1);
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_setxattr_in_size(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_setxattr_in *arg1 = (struct fuse_setxattr_in *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_setxattr_in *)jarg1; 
    result = (unsigned int) ((arg1)->size);
    
    jresult = result; 
    return jresult;
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_setxattr_in_flags(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_setxattr_in *arg1 = (struct fuse_setxattr_in *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_setxattr_in *)jarg1; 
    result = (unsigned int) ((arg1)->flags);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_fuse_setxattr_in_copyFrom(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct fuse_setxattr_in *arg1 = (struct fuse_setxattr_in *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct fuse_setxattr_in *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)fuse_setxattr_in_copyFrom(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_fuse_setxattr_in() {
    void * jresult = 0 ;
    struct fuse_setxattr_in *result;
    
    result = (struct fuse_setxattr_in *)(struct fuse_setxattr_in *) calloc(1, sizeof(struct fuse_setxattr_in));
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_fuse_setxattr_in(void * jarg1) {
    struct fuse_setxattr_in *arg1 = (struct fuse_setxattr_in *) 0 ;
    
    arg1 = (struct fuse_setxattr_in *)jarg1; 
    free((char *) arg1);
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_getxattr_in_size(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_getxattr_in *arg1 = (struct fuse_getxattr_in *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_getxattr_in *)jarg1; 
    result = (unsigned int) ((arg1)->size);
    
    jresult = result; 
    return jresult;
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_getxattr_in_padding(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_getxattr_in *arg1 = (struct fuse_getxattr_in *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_getxattr_in *)jarg1; 
    result = (unsigned int) ((arg1)->padding);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_fuse_getxattr_in_copyFrom(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct fuse_getxattr_in *arg1 = (struct fuse_getxattr_in *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct fuse_getxattr_in *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)fuse_getxattr_in_copyFrom(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_fuse_getxattr_in() {
    void * jresult = 0 ;
    struct fuse_getxattr_in *result;
    
    result = (struct fuse_getxattr_in *)(struct fuse_getxattr_in *) calloc(1, sizeof(struct fuse_getxattr_in));
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_fuse_getxattr_in(void * jarg1) {
    struct fuse_getxattr_in *arg1 = (struct fuse_getxattr_in *) 0 ;
    
    arg1 = (struct fuse_getxattr_in *)jarg1; 
    free((char *) arg1);
    
}


DllExport void SWIGSTDCALL CSharp_set_fuse_getxattr_out_size(void * jarg1, unsigned int jarg2) {
    struct fuse_getxattr_out *arg1 = (struct fuse_getxattr_out *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_getxattr_out *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->size = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_getxattr_out_size(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_getxattr_out *arg1 = (struct fuse_getxattr_out *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_getxattr_out *)jarg1; 
    result = (unsigned int) ((arg1)->size);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_getxattr_out_padding(void * jarg1, unsigned int jarg2) {
    struct fuse_getxattr_out *arg1 = (struct fuse_getxattr_out *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_getxattr_out *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->padding = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_getxattr_out_padding(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_getxattr_out *arg1 = (struct fuse_getxattr_out *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_getxattr_out *)jarg1; 
    result = (unsigned int) ((arg1)->padding);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_fuse_getxattr_out_copyTo(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct fuse_getxattr_out *arg1 = (struct fuse_getxattr_out *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct fuse_getxattr_out *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)fuse_getxattr_out_copyTo(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_fuse_getxattr_out() {
    void * jresult = 0 ;
    struct fuse_getxattr_out *result;
    
    result = (struct fuse_getxattr_out *)(struct fuse_getxattr_out *) calloc(1, sizeof(struct fuse_getxattr_out));
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_fuse_getxattr_out(void * jarg1) {
    struct fuse_getxattr_out *arg1 = (struct fuse_getxattr_out *) 0 ;
    
    arg1 = (struct fuse_getxattr_out *)jarg1; 
    free((char *) arg1);
    
}


DllExport void SWIGSTDCALL CSharp_set_fuse_init_in_out_major(void * jarg1, unsigned int jarg2) {
    struct fuse_init_in_out *arg1 = (struct fuse_init_in_out *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_init_in_out *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->major = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_init_in_out_major(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_init_in_out *arg1 = (struct fuse_init_in_out *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_init_in_out *)jarg1; 
    result = (unsigned int) ((arg1)->major);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_init_in_out_minor(void * jarg1, unsigned int jarg2) {
    struct fuse_init_in_out *arg1 = (struct fuse_init_in_out *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_init_in_out *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->minor = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_init_in_out_minor(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_init_in_out *arg1 = (struct fuse_init_in_out *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_init_in_out *)jarg1; 
    result = (unsigned int) ((arg1)->minor);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_fuse_init_in_out_copyFrom(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct fuse_init_in_out *arg1 = (struct fuse_init_in_out *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct fuse_init_in_out *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)fuse_init_in_out_copyFrom(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_fuse_init_in_out_copyTo(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct fuse_init_in_out *arg1 = (struct fuse_init_in_out *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct fuse_init_in_out *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)fuse_init_in_out_copyTo(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_fuse_init_in_out() {
    void * jresult = 0 ;
    struct fuse_init_in_out *result;
    
    result = (struct fuse_init_in_out *)(struct fuse_init_in_out *) calloc(1, sizeof(struct fuse_init_in_out));
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_fuse_init_in_out(void * jarg1) {
    struct fuse_init_in_out *arg1 = (struct fuse_init_in_out *) 0 ;
    
    arg1 = (struct fuse_init_in_out *)jarg1; 
    free((char *) arg1);
    
}


DllExport void SWIGSTDCALL CSharp_set_fuse_in_header_len(void * jarg1, unsigned int jarg2) {
    struct fuse_in_header *arg1 = (struct fuse_in_header *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_in_header *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->len = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_in_header_len(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_in_header *arg1 = (struct fuse_in_header *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_in_header *)jarg1; 
    result = (unsigned int) ((arg1)->len);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_in_header_opcode(void * jarg1, unsigned int jarg2) {
    struct fuse_in_header *arg1 = (struct fuse_in_header *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_in_header *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->opcode = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_in_header_opcode(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_in_header *arg1 = (struct fuse_in_header *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_in_header *)jarg1; 
    result = (unsigned int) ((arg1)->opcode);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_in_header_unique(void * jarg1, unsigned long long jarg2) {
    struct fuse_in_header *arg1 = (struct fuse_in_header *) 0 ;
    unsigned long long arg2 ;
    
    arg1 = (struct fuse_in_header *)jarg1; 
    arg2 = (unsigned long long)jarg2; 
    if (arg1) (arg1)->unique = arg2;
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_in_header_unique(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_in_header *arg1 = (struct fuse_in_header *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_in_header *)jarg1; 
    result = (unsigned long long) ((arg1)->unique);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_in_header_nodeid(void * jarg1, unsigned long long jarg2) {
    struct fuse_in_header *arg1 = (struct fuse_in_header *) 0 ;
    unsigned long long arg2 ;
    
    arg1 = (struct fuse_in_header *)jarg1; 
    arg2 = (unsigned long long)jarg2; 
    if (arg1) (arg1)->nodeid = arg2;
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_in_header_nodeid(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_in_header *arg1 = (struct fuse_in_header *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_in_header *)jarg1; 
    result = (unsigned long long) ((arg1)->nodeid);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_in_header_uid(void * jarg1, unsigned int jarg2) {
    struct fuse_in_header *arg1 = (struct fuse_in_header *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_in_header *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->uid = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_in_header_uid(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_in_header *arg1 = (struct fuse_in_header *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_in_header *)jarg1; 
    result = (unsigned int) ((arg1)->uid);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_in_header_gid(void * jarg1, unsigned int jarg2) {
    struct fuse_in_header *arg1 = (struct fuse_in_header *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_in_header *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->gid = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_in_header_gid(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_in_header *arg1 = (struct fuse_in_header *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_in_header *)jarg1; 
    result = (unsigned int) ((arg1)->gid);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_in_header_pid(void * jarg1, unsigned int jarg2) {
    struct fuse_in_header *arg1 = (struct fuse_in_header *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_in_header *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->pid = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_in_header_pid(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_in_header *arg1 = (struct fuse_in_header *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_in_header *)jarg1; 
    result = (unsigned int) ((arg1)->pid);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_in_header_padding(void * jarg1, unsigned int jarg2) {
    struct fuse_in_header *arg1 = (struct fuse_in_header *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_in_header *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->padding = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_in_header_padding(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_in_header *arg1 = (struct fuse_in_header *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_in_header *)jarg1; 
    result = (unsigned int) ((arg1)->padding);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_fuse_in_header_copyFrom(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct fuse_in_header *arg1 = (struct fuse_in_header *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct fuse_in_header *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)fuse_in_header_copyFrom(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_fuse_in_header_structSize() {
    int jresult = 0 ;
    int result;
    
    result = (int)fuse_in_header_structSize();
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_fuse_in_header() {
    void * jresult = 0 ;
    struct fuse_in_header *result;
    
    result = (struct fuse_in_header *)(struct fuse_in_header *) calloc(1, sizeof(struct fuse_in_header));
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_fuse_in_header(void * jarg1) {
    struct fuse_in_header *arg1 = (struct fuse_in_header *) 0 ;
    
    arg1 = (struct fuse_in_header *)jarg1; 
    free((char *) arg1);
    
}


DllExport void SWIGSTDCALL CSharp_set_fuse_out_header_len(void * jarg1, unsigned int jarg2) {
    struct fuse_out_header *arg1 = (struct fuse_out_header *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_out_header *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->len = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_out_header_len(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_out_header *arg1 = (struct fuse_out_header *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_out_header *)jarg1; 
    result = (unsigned int) ((arg1)->len);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_out_header_error(void * jarg1, int jarg2) {
    struct fuse_out_header *arg1 = (struct fuse_out_header *) 0 ;
    int arg2 ;
    
    arg1 = (struct fuse_out_header *)jarg1; 
    arg2 = (int)jarg2; 
    if (arg1) (arg1)->error = arg2;
    
}


DllExport int SWIGSTDCALL CSharp_get_fuse_out_header_error(void * jarg1) {
    int jresult = 0 ;
    struct fuse_out_header *arg1 = (struct fuse_out_header *) 0 ;
    int result;
    
    arg1 = (struct fuse_out_header *)jarg1; 
    result = (int) ((arg1)->error);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_out_header_unique(void * jarg1, unsigned long long jarg2) {
    struct fuse_out_header *arg1 = (struct fuse_out_header *) 0 ;
    unsigned long long arg2 ;
    
    arg1 = (struct fuse_out_header *)jarg1; 
    arg2 = (unsigned long long)jarg2; 
    if (arg1) (arg1)->unique = arg2;
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_out_header_unique(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_out_header *arg1 = (struct fuse_out_header *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_out_header *)jarg1; 
    result = (unsigned long long) ((arg1)->unique);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_fuse_out_header_copyTo(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct fuse_out_header *arg1 = (struct fuse_out_header *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct fuse_out_header *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)fuse_out_header_copyTo(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_fuse_out_header() {
    void * jresult = 0 ;
    struct fuse_out_header *result;
    
    result = (struct fuse_out_header *)(struct fuse_out_header *) calloc(1, sizeof(struct fuse_out_header));
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_fuse_out_header(void * jarg1) {
    struct fuse_out_header *arg1 = (struct fuse_out_header *) 0 ;
    
    arg1 = (struct fuse_out_header *)jarg1; 
    free((char *) arg1);
    
}


DllExport void SWIGSTDCALL CSharp_set_fuse_dirent_ino(void * jarg1, unsigned long long jarg2) {
    struct fuse_dirent *arg1 = (struct fuse_dirent *) 0 ;
    unsigned long long arg2 ;
    
    arg1 = (struct fuse_dirent *)jarg1; 
    arg2 = (unsigned long long)jarg2; 
    if (arg1) (arg1)->ino = arg2;
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_dirent_ino(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_dirent *arg1 = (struct fuse_dirent *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_dirent *)jarg1; 
    result = (unsigned long long) ((arg1)->ino);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_dirent_off(void * jarg1, unsigned long long jarg2) {
    struct fuse_dirent *arg1 = (struct fuse_dirent *) 0 ;
    unsigned long long arg2 ;
    
    arg1 = (struct fuse_dirent *)jarg1; 
    arg2 = (unsigned long long)jarg2; 
    if (arg1) (arg1)->off = arg2;
    
}


DllExport unsigned long long SWIGSTDCALL CSharp_get_fuse_dirent_off(void * jarg1) {
    unsigned long long jresult = 0 ;
    struct fuse_dirent *arg1 = (struct fuse_dirent *) 0 ;
    unsigned long long result;
    
    arg1 = (struct fuse_dirent *)jarg1; 
    result = (unsigned long long) ((arg1)->off);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_dirent_namelen(void * jarg1, unsigned int jarg2) {
    struct fuse_dirent *arg1 = (struct fuse_dirent *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_dirent *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->namelen = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_dirent_namelen(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_dirent *arg1 = (struct fuse_dirent *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_dirent *)jarg1; 
    result = (unsigned int) ((arg1)->namelen);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_dirent_type(void * jarg1, unsigned int jarg2) {
    struct fuse_dirent *arg1 = (struct fuse_dirent *) 0 ;
    unsigned int arg2 ;
    
    arg1 = (struct fuse_dirent *)jarg1; 
    arg2 = (unsigned int)jarg2; 
    if (arg1) (arg1)->type = arg2;
    
}


DllExport unsigned int SWIGSTDCALL CSharp_get_fuse_dirent_type(void * jarg1) {
    unsigned int jresult = 0 ;
    struct fuse_dirent *arg1 = (struct fuse_dirent *) 0 ;
    unsigned int result;
    
    arg1 = (struct fuse_dirent *)jarg1; 
    result = (unsigned int) ((arg1)->type);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_set_fuse_dirent_name(void * jarg1, char * jarg2) {
    struct fuse_dirent *arg1 = (struct fuse_dirent *) 0 ;
    char *arg2 ;
    
    arg1 = (struct fuse_dirent *)jarg1; 
    arg2 = jarg2; 
    {
        if (arg2) strncpy(arg1->name,arg2,0);
        else arg1->name[0] = 0;
    }
}


DllExport char * SWIGSTDCALL CSharp_get_fuse_dirent_name(void * jarg1) {
    char * jresult = 0 ;
    struct fuse_dirent *arg1 = (struct fuse_dirent *) 0 ;
    char *result;
    
    arg1 = (struct fuse_dirent *)jarg1; 
    result = (char *)(char *) ((arg1)->name);
    
    jresult = SWIG_csharp_string_callback(result); 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_fuse_dirent() {
    void * jresult = 0 ;
    struct fuse_dirent *result;
    
    result = (struct fuse_dirent *)(struct fuse_dirent *) calloc(1, sizeof(struct fuse_dirent));
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_fuse_dirent(void * jarg1) {
    struct fuse_dirent *arg1 = (struct fuse_dirent *) 0 ;
    
    arg1 = (struct fuse_dirent *)jarg1; 
    free((char *) arg1);
    
}


DllExport void SWIGSTDCALL CSharp_set_FWBuffer_offset(void * jarg1, int jarg2) {
    struct FWBuffer *arg1 = (struct FWBuffer *) 0 ;
    int arg2 ;
    
    arg1 = (struct FWBuffer *)jarg1; 
    arg2 = (int)jarg2; 
    if (arg1) (arg1)->offset = arg2;
    
}


DllExport int SWIGSTDCALL CSharp_get_FWBuffer_offset(void * jarg1) {
    int jresult = 0 ;
    struct FWBuffer *arg1 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct FWBuffer *)jarg1; 
    result = (int) ((arg1)->offset);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_get_FWBuffer_initialized(void * jarg1) {
    int jresult = 0 ;
    struct FWBuffer *arg1 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct FWBuffer *)jarg1; 
    result = (int) ((arg1)->initialized);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_get_FWBuffer_length(void * jarg1) {
    int jresult = 0 ;
    struct FWBuffer *arg1 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct FWBuffer *)jarg1; 
    result = (int) ((arg1)->length);
    
    jresult = result; 
    return jresult;
}


DllExport char * SWIGSTDCALL CSharp_get_FWBuffer_data(void * jarg1) {
    char * jresult = 0 ;
    struct FWBuffer *arg1 = (struct FWBuffer *) 0 ;
    char *result;
    
    arg1 = (struct FWBuffer *)jarg1; 
    result = (char *) ((arg1)->data);
    
    jresult = SWIG_csharp_string_callback(result); 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_FWBuffer(int jarg1) {
    void * jresult = 0 ;
    int arg1 ;
    struct FWBuffer *result;
    
    arg1 = (int)jarg1; 
    result = (struct FWBuffer *)new_FWBuffer(arg1);
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_FWBuffer(void * jarg1) {
    struct FWBuffer *arg1 = (struct FWBuffer *) 0 ;
    
    arg1 = (struct FWBuffer *)jarg1; 
    delete_FWBuffer(arg1);
    
}


DllExport void SWIGSTDCALL CSharp_FWBuffer_Rewind(void * jarg1) {
    struct FWBuffer *arg1 = (struct FWBuffer *) 0 ;
    
    arg1 = (struct FWBuffer *)jarg1; 
    FWBuffer_Rewind(arg1);
    
}


DllExport void SWIGSTDCALL CSharp_FWBuffer_Reset(void * jarg1) {
    struct FWBuffer *arg1 = (struct FWBuffer *) 0 ;
    
    arg1 = (struct FWBuffer *)jarg1; 
    FWBuffer_Reset(arg1);
    
}


DllExport int SWIGSTDCALL CSharp_FWBuffer_EnsureFreeSpace(void * jarg1, int jarg2) {
    int jresult = 0 ;
    struct FWBuffer *arg1 = (struct FWBuffer *) 0 ;
    int arg2 ;
    int result;
    
    arg1 = (struct FWBuffer *)jarg1; 
    arg2 = (int)jarg2; 
    result = (int)FWBuffer_EnsureFreeSpace(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_FWBuffer_Read__SWIG_0(void * jarg1, int jarg2) {
    int jresult = 0 ;
    struct FWBuffer *arg1 = (struct FWBuffer *) 0 ;
    int arg2 ;
    int result;
    
    arg1 = (struct FWBuffer *)jarg1; 
    arg2 = (int)jarg2; 
    SWIG_contract_assert(0, (arg2>=0), "Contract violation: require: (arg2>=0)");
    
    result = (int)FWBuffer_Read__SWIG_0(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_FWBuffer_Read__SWIG_1(void * jarg1, int jarg2, unsigned long jarg3, unsigned long long jarg4) {
    int jresult = 0 ;
    struct FWBuffer *arg1 = (struct FWBuffer *) 0 ;
    int arg2 ;
    size_t arg3 ;
    __u64 arg4 ;
    int result;
    
    arg1 = (struct FWBuffer *)jarg1; 
    arg2 = (int)jarg2; 
    arg3 = (size_t)jarg3; 
    arg4 = (__u64)jarg4; 
    result = (int)FWBuffer_Read__SWIG_1(arg1,arg2,arg3,arg4);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_FWBuffer_Write__SWIG_0(void * jarg1, int jarg2, unsigned long jarg3, unsigned long long jarg4) {
    int jresult = 0 ;
    struct FWBuffer *arg1 = (struct FWBuffer *) 0 ;
    int arg2 ;
    size_t arg3 ;
    __u64 arg4 ;
    int result;
    
    arg1 = (struct FWBuffer *)jarg1; 
    arg2 = (int)jarg2; 
    arg3 = (size_t)jarg3; 
    arg4 = (__u64)jarg4; 
    result = (int)FWBuffer_Write__SWIG_0(arg1,arg2,arg3,arg4);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_FWBuffer_Write__SWIG_1(void * jarg1, int jarg2) {
    int jresult = 0 ;
    struct FWBuffer *arg1 = (struct FWBuffer *) 0 ;
    int arg2 ;
    int result;
    
    arg1 = (struct FWBuffer *)jarg1; 
    arg2 = (int)jarg2; 
    SWIG_contract_assert(0, (arg2>=0), "Contract violation: require: (arg2>=0)");
    
    result = (int)FWBuffer_Write__SWIG_1(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport char * SWIGSTDCALL CSharp_FWBuffer_GetString(void * jarg1) {
    char * jresult = 0 ;
    struct FWBuffer *arg1 = (struct FWBuffer *) 0 ;
    char *result;
    
    arg1 = (struct FWBuffer *)jarg1; 
    result = (char *)FWBuffer_GetString(arg1);
    
    jresult = SWIG_csharp_string_callback(result); 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_FWBuffer_GetBytes(void * jarg1, char * jarg2, int jarg3) {
    int jresult = 0 ;
    struct FWBuffer *arg1 = (struct FWBuffer *) 0 ;
    char *arg2 = (char *) 0 ;
    int arg3 ;
    int result;
    
    arg1 = (struct FWBuffer *)jarg1; 
    arg2 = jarg2; 
    arg3 = (int)jarg3; 
    result = (int)FWBuffer_GetBytes(arg1,arg2,arg3);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_FWBuffer_GetByte(void * jarg1) {
    int jresult = 0 ;
    struct FWBuffer *arg1 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct FWBuffer *)jarg1; 
    result = (int)FWBuffer_GetByte(arg1);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_FWBuffer_AddBytes(void * jarg1, char * jarg2, int jarg3) {
    int jresult = 0 ;
    struct FWBuffer *arg1 = (struct FWBuffer *) 0 ;
    char *arg2 = (char *) 0 ;
    int arg3 ;
    int result;
    
    arg1 = (struct FWBuffer *)jarg1; 
    arg2 = jarg2; 
    arg3 = (int)jarg3; 
    result = (int)FWBuffer_AddBytes(arg1,(char const *)arg2,arg3);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_FWBuffer_AddChar(void * jarg1, int jarg2, char jarg3) {
    int jresult = 0 ;
    struct FWBuffer *arg1 = (struct FWBuffer *) 0 ;
    int arg2 ;
    char arg3 ;
    int result;
    
    arg1 = (struct FWBuffer *)jarg1; 
    arg2 = (int)jarg2; 
    arg3 = (char)jarg3; 
    result = (int)FWBuffer_AddChar(arg1,arg2,arg3);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_FWBuffer_AddString(void * jarg1, char * jarg2) {
    int jresult = 0 ;
    struct FWBuffer *arg1 = (struct FWBuffer *) 0 ;
    char *arg2 = (char *) 0 ;
    int result;
    
    arg1 = (struct FWBuffer *)jarg1; 
    arg2 = jarg2; 
    result = (int)FWBuffer_AddString(arg1,(char const *)arg2);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_FWBuffer_AddSubString(void * jarg1, char * jarg2, int jarg3, int jarg4) {
    int jresult = 0 ;
    struct FWBuffer *arg1 = (struct FWBuffer *) 0 ;
    char *arg2 = (char *) 0 ;
    int arg3 ;
    int arg4 ;
    int result;
    
    arg1 = (struct FWBuffer *)jarg1; 
    arg2 = jarg2; 
    arg3 = (int)jarg3; 
    arg4 = (int)jarg4; 
    result = (int)FWBuffer_AddSubString(arg1,(char const *)arg2,arg3,arg4);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_FWBuffer_AddBuffer(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct FWBuffer *arg1 = (struct FWBuffer *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct FWBuffer *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)FWBuffer_AddBuffer(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_FWBuffer_copyTo(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct FWBuffer *arg1 = (struct FWBuffer *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct FWBuffer *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)FWBuffer_copyTo(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_get_FileBuffer_buf(void * jarg1) {
    void * jresult = 0 ;
    struct FileBuffer *arg1 = (struct FileBuffer *) 0 ;
    struct FWBuffer *result;
    
    arg1 = (struct FileBuffer *)jarg1; 
    result = (struct FWBuffer *) ((arg1)->buf);
    
    jresult = (void *)result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_get_FileBuffer_error(void * jarg1) {
    int jresult = 0 ;
    struct FileBuffer *arg1 = (struct FileBuffer *) 0 ;
    int result;
    
    arg1 = (struct FileBuffer *)jarg1; 
    result = (int) ((arg1)->error);
    
    jresult = result; 
    return jresult;
}


DllExport void * SWIGSTDCALL CSharp_new_FileBuffer(void * jarg1) {
    void * jresult = 0 ;
    struct FWBuffer *arg1 = (struct FWBuffer *) 0 ;
    struct FileBuffer *result;
    
    arg1 = (struct FWBuffer *)jarg1; 
    result = (struct FileBuffer *)new_FileBuffer(arg1);
    
    jresult = (void *)result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_delete_FileBuffer(void * jarg1) {
    struct FileBuffer *arg1 = (struct FileBuffer *) 0 ;
    
    arg1 = (struct FileBuffer *)jarg1; 
    delete_FileBuffer(arg1);
    
}


DllExport int SWIGSTDCALL CSharp_FileBuffer_addFile(void * jarg1, char * jarg2, unsigned long long jarg3, unsigned int jarg4, unsigned long long jarg5) {
    int jresult = 0 ;
    struct FileBuffer *arg1 = (struct FileBuffer *) 0 ;
    char *arg2 = (char *) 0 ;
    __u64 arg3 ;
    __u32 arg4 ;
    __u64 arg5 ;
    int result;
    
    arg1 = (struct FileBuffer *)jarg1; 
    arg2 = jarg2; 
    arg3 = (__u64)jarg3; 
    arg4 = (__u32)jarg4; 
    arg5 = (__u64)jarg5; 
    result = (int)FileBuffer_addFile(arg1,(char const *)arg2,arg3,arg4,arg5);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_FileBuffer_copyTo(void * jarg1, void * jarg2) {
    int jresult = 0 ;
    struct FileBuffer *arg1 = (struct FileBuffer *) 0 ;
    struct FWBuffer *arg2 = (struct FWBuffer *) 0 ;
    int result;
    
    arg1 = (struct FileBuffer *)jarg1; 
    arg2 = (struct FWBuffer *)jarg2; 
    result = (int)FileBuffer_copyTo(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


#ifdef __cplusplus
}
#endif

