/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

class FuseWrapperPINVOKE {

  class SWIGExceptionHelper {

    public delegate void SWIGExceptionDelegate(string message);

    static SWIGExceptionDelegate systemDelegate = new SWIGExceptionDelegate(ThrowSystemException);
    static SWIGExceptionDelegate outOfMemoryDelegate = new SWIGExceptionDelegate(ThrowOutOfMemoryException);
    static SWIGExceptionDelegate indexOutOfRangeDelegate = new SWIGExceptionDelegate(ThrowIndexOutOfRangeException);
    static SWIGExceptionDelegate divideByZeroDelegate = new SWIGExceptionDelegate(ThrowDivideByZeroException);
    static SWIGExceptionDelegate argumentOutOfRangeDelegate = new SWIGExceptionDelegate(ThrowArgumentOutOfRangeException);
    static SWIGExceptionDelegate nullReferenceDelegate = new SWIGExceptionDelegate(ThrowNullReferenceException);

    [DllImport("FuseWrapper", EntryPoint="SWIGRegisterExceptionCallbacks_FuseWrapper")]
    public static extern void SWIGRegisterExceptionCallbacks_FuseWrapper(
      SWIGExceptionDelegate systemExceptionDelegate,
      SWIGExceptionDelegate outOfMemoryDelegate, 
      SWIGExceptionDelegate indexOutOfRangeDelegate, 
      SWIGExceptionDelegate divideByZeroDelegate, 
      SWIGExceptionDelegate argumentOutOfRangeDelegate,
      SWIGExceptionDelegate nullReferenceDelegate);

    static void ThrowSystemException(string message) {
      throw new System.SystemException(message);
    }

    static void ThrowOutOfMemoryException(string message) {
      throw new System.OutOfMemoryException(message);
    }

    static void ThrowIndexOutOfRangeException(string message) {
      throw new System.IndexOutOfRangeException(message);
    }

    static void ThrowDivideByZeroException(string message) {
      throw new System.DivideByZeroException(message);
    }

    static void ThrowArgumentOutOfRangeException(string message) {
      throw new System.ArgumentOutOfRangeException(message);
    }

    static void ThrowNullReferenceException(string message) {
      throw new System.NullReferenceException(message);
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_FuseWrapper(systemDelegate, outOfMemoryDelegate, indexOutOfRangeDelegate, divideByZeroDelegate, argumentOutOfRangeDelegate, nullReferenceDelegate);
    }
  }

  static SWIGExceptionHelper exceptionHelper = new SWIGExceptionHelper();


  class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [DllImport("FuseWrapper", EntryPoint="SWIGRegisterStringCallback_FuseWrapper")]
    public static extern void SWIGRegisterStringCallback_FuseWrapper(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_FuseWrapper(stringDelegate);
    }
  }

  static SWIGStringHelper stringHelper = new SWIGStringHelper();


  [DllImport("FuseWrapper", EntryPoint="CSharp_get__FILE_OFFSET_BITS")]
  public static extern int get__FILE_OFFSET_BITS();

  [DllImport("FuseWrapper", EntryPoint="CSharp_close_fd")]
  public static extern int close_fd(int jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_attr_ino")]
  public static extern void set_fuse_attr_ino(IntPtr jarg1, ulong jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_attr_ino")]
  public static extern ulong get_fuse_attr_ino(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_attr_size")]
  public static extern void set_fuse_attr_size(IntPtr jarg1, ulong jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_attr_size")]
  public static extern ulong get_fuse_attr_size(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_attr_blocks")]
  public static extern void set_fuse_attr_blocks(IntPtr jarg1, ulong jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_attr_blocks")]
  public static extern ulong get_fuse_attr_blocks(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_attr_atime")]
  public static extern void set_fuse_attr_atime(IntPtr jarg1, ulong jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_attr_atime")]
  public static extern ulong get_fuse_attr_atime(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_attr_mtime")]
  public static extern void set_fuse_attr_mtime(IntPtr jarg1, ulong jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_attr_mtime")]
  public static extern ulong get_fuse_attr_mtime(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_attr_ctime")]
  public static extern void set_fuse_attr_ctime(IntPtr jarg1, ulong jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_attr_ctime")]
  public static extern ulong get_fuse_attr_ctime(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_attr_atimensec")]
  public static extern void set_fuse_attr_atimensec(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_attr_atimensec")]
  public static extern uint get_fuse_attr_atimensec(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_attr_mtimensec")]
  public static extern void set_fuse_attr_mtimensec(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_attr_mtimensec")]
  public static extern uint get_fuse_attr_mtimensec(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_attr_ctimensec")]
  public static extern void set_fuse_attr_ctimensec(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_attr_ctimensec")]
  public static extern uint get_fuse_attr_ctimensec(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_attr_mode")]
  public static extern void set_fuse_attr_mode(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_attr_mode")]
  public static extern uint get_fuse_attr_mode(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_attr_nlink")]
  public static extern void set_fuse_attr_nlink(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_attr_nlink")]
  public static extern uint get_fuse_attr_nlink(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_attr_uid")]
  public static extern void set_fuse_attr_uid(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_attr_uid")]
  public static extern uint get_fuse_attr_uid(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_attr_gid")]
  public static extern void set_fuse_attr_gid(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_attr_gid")]
  public static extern uint get_fuse_attr_gid(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_attr_rdev")]
  public static extern void set_fuse_attr_rdev(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_attr_rdev")]
  public static extern uint get_fuse_attr_rdev(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_fuse_attr")]
  public static extern IntPtr new_fuse_attr();

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_fuse_attr")]
  public static extern void delete_fuse_attr(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_kstatfs_blocks")]
  public static extern void set_fuse_kstatfs_blocks(IntPtr jarg1, ulong jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_kstatfs_blocks")]
  public static extern ulong get_fuse_kstatfs_blocks(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_kstatfs_bfree")]
  public static extern void set_fuse_kstatfs_bfree(IntPtr jarg1, ulong jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_kstatfs_bfree")]
  public static extern ulong get_fuse_kstatfs_bfree(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_kstatfs_bavail")]
  public static extern void set_fuse_kstatfs_bavail(IntPtr jarg1, ulong jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_kstatfs_bavail")]
  public static extern ulong get_fuse_kstatfs_bavail(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_kstatfs_files")]
  public static extern void set_fuse_kstatfs_files(IntPtr jarg1, ulong jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_kstatfs_files")]
  public static extern ulong get_fuse_kstatfs_files(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_kstatfs_ffree")]
  public static extern void set_fuse_kstatfs_ffree(IntPtr jarg1, ulong jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_kstatfs_ffree")]
  public static extern ulong get_fuse_kstatfs_ffree(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_kstatfs_bsize")]
  public static extern void set_fuse_kstatfs_bsize(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_kstatfs_bsize")]
  public static extern uint get_fuse_kstatfs_bsize(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_kstatfs_namelen")]
  public static extern void set_fuse_kstatfs_namelen(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_kstatfs_namelen")]
  public static extern uint get_fuse_kstatfs_namelen(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_fuse_kstatfs")]
  public static extern IntPtr new_fuse_kstatfs();

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_fuse_kstatfs")]
  public static extern void delete_fuse_kstatfs(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_entry_out_nodeid")]
  public static extern void set_fuse_entry_out_nodeid(IntPtr jarg1, ulong jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_entry_out_nodeid")]
  public static extern ulong get_fuse_entry_out_nodeid(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_entry_out_generation")]
  public static extern void set_fuse_entry_out_generation(IntPtr jarg1, ulong jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_entry_out_generation")]
  public static extern ulong get_fuse_entry_out_generation(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_entry_out_entry_valid")]
  public static extern void set_fuse_entry_out_entry_valid(IntPtr jarg1, ulong jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_entry_out_entry_valid")]
  public static extern ulong get_fuse_entry_out_entry_valid(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_entry_out_attr_valid")]
  public static extern void set_fuse_entry_out_attr_valid(IntPtr jarg1, ulong jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_entry_out_attr_valid")]
  public static extern ulong get_fuse_entry_out_attr_valid(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_entry_out_entry_valid_nsec")]
  public static extern void set_fuse_entry_out_entry_valid_nsec(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_entry_out_entry_valid_nsec")]
  public static extern uint get_fuse_entry_out_entry_valid_nsec(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_entry_out_attr_valid_nsec")]
  public static extern void set_fuse_entry_out_attr_valid_nsec(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_entry_out_attr_valid_nsec")]
  public static extern uint get_fuse_entry_out_attr_valid_nsec(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_entry_out_attr")]
  public static extern void set_fuse_entry_out_attr(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_entry_out_attr")]
  public static extern IntPtr get_fuse_entry_out_attr(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_fuse_entry_out_copyTo")]
  public static extern int fuse_entry_out_copyTo(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_fuse_entry_out")]
  public static extern IntPtr new_fuse_entry_out();

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_fuse_entry_out")]
  public static extern void delete_fuse_entry_out(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_forget_in_version")]
  public static extern ulong get_fuse_forget_in_version(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_fuse_forget_in_copyFrom")]
  public static extern int fuse_forget_in_copyFrom(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_fuse_forget_in")]
  public static extern IntPtr new_fuse_forget_in();

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_fuse_forget_in")]
  public static extern void delete_fuse_forget_in(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_attr_out_attr_valid")]
  public static extern void set_fuse_attr_out_attr_valid(IntPtr jarg1, ulong jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_attr_out_attr_valid")]
  public static extern ulong get_fuse_attr_out_attr_valid(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_attr_out_attr_valid_nsec")]
  public static extern void set_fuse_attr_out_attr_valid_nsec(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_attr_out_attr_valid_nsec")]
  public static extern uint get_fuse_attr_out_attr_valid_nsec(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_attr_out_dummy")]
  public static extern void set_fuse_attr_out_dummy(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_attr_out_dummy")]
  public static extern uint get_fuse_attr_out_dummy(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_attr_out_attr")]
  public static extern void set_fuse_attr_out_attr(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_attr_out_attr")]
  public static extern IntPtr get_fuse_attr_out_attr(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_fuse_attr_out_copyTo")]
  public static extern int fuse_attr_out_copyTo(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_fuse_attr_out")]
  public static extern IntPtr new_fuse_attr_out();

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_fuse_attr_out")]
  public static extern void delete_fuse_attr_out(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_mknod_in_mode")]
  public static extern uint get_fuse_mknod_in_mode(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_mknod_in_rdev")]
  public static extern uint get_fuse_mknod_in_rdev(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_fuse_mknod_in_copyFrom")]
  public static extern int fuse_mknod_in_copyFrom(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_fuse_mknod_in")]
  public static extern IntPtr new_fuse_mknod_in();

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_fuse_mknod_in")]
  public static extern void delete_fuse_mknod_in(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_mkdir_in_mode")]
  public static extern uint get_fuse_mkdir_in_mode(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_mkdir_in_padding")]
  public static extern uint get_fuse_mkdir_in_padding(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_fuse_mkdir_in_copyFrom")]
  public static extern int fuse_mkdir_in_copyFrom(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_fuse_mkdir_in")]
  public static extern IntPtr new_fuse_mkdir_in();

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_fuse_mkdir_in")]
  public static extern void delete_fuse_mkdir_in(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_rename_in_newdir")]
  public static extern ulong get_fuse_rename_in_newdir(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_fuse_rename_in_copyFrom")]
  public static extern int fuse_rename_in_copyFrom(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_fuse_rename_in")]
  public static extern IntPtr new_fuse_rename_in();

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_fuse_rename_in")]
  public static extern void delete_fuse_rename_in(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_link_in_oldnodeid")]
  public static extern ulong get_fuse_link_in_oldnodeid(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_fuse_link_in_copyFrom")]
  public static extern int fuse_link_in_copyFrom(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_fuse_link_in")]
  public static extern IntPtr new_fuse_link_in();

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_fuse_link_in")]
  public static extern void delete_fuse_link_in(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_setattr_in_valid")]
  public static extern uint get_fuse_setattr_in_valid(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_setattr_in_padding")]
  public static extern uint get_fuse_setattr_in_padding(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_setattr_in_attr")]
  public static extern IntPtr get_fuse_setattr_in_attr(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_fuse_setattr_in_copyFrom")]
  public static extern int fuse_setattr_in_copyFrom(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_fuse_setattr_in")]
  public static extern IntPtr new_fuse_setattr_in();

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_fuse_setattr_in")]
  public static extern void delete_fuse_setattr_in(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_open_in_flags")]
  public static extern uint get_fuse_open_in_flags(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_open_in_padding")]
  public static extern uint get_fuse_open_in_padding(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_fuse_open_in_copyFrom")]
  public static extern int fuse_open_in_copyFrom(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_fuse_open_in")]
  public static extern IntPtr new_fuse_open_in();

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_fuse_open_in")]
  public static extern void delete_fuse_open_in(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_open_out_fh")]
  public static extern void set_fuse_open_out_fh(IntPtr jarg1, ulong jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_open_out_fh")]
  public static extern ulong get_fuse_open_out_fh(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_open_out_open_flags")]
  public static extern void set_fuse_open_out_open_flags(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_open_out_open_flags")]
  public static extern uint get_fuse_open_out_open_flags(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_open_out_padding")]
  public static extern void set_fuse_open_out_padding(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_open_out_padding")]
  public static extern uint get_fuse_open_out_padding(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_fuse_open_out_copyTo")]
  public static extern int fuse_open_out_copyTo(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_fuse_open_out")]
  public static extern IntPtr new_fuse_open_out();

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_fuse_open_out")]
  public static extern void delete_fuse_open_out(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_release_in_fh")]
  public static extern ulong get_fuse_release_in_fh(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_release_in_flags")]
  public static extern uint get_fuse_release_in_flags(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_release_in_padding")]
  public static extern uint get_fuse_release_in_padding(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_fuse_release_in_copyFrom")]
  public static extern int fuse_release_in_copyFrom(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_fuse_release_in")]
  public static extern IntPtr new_fuse_release_in();

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_fuse_release_in")]
  public static extern void delete_fuse_release_in(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_flush_in_fh")]
  public static extern ulong get_fuse_flush_in_fh(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_flush_in_flush_flags")]
  public static extern uint get_fuse_flush_in_flush_flags(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_flush_in_padding")]
  public static extern uint get_fuse_flush_in_padding(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_fuse_flush_in_copyFrom")]
  public static extern int fuse_flush_in_copyFrom(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_fuse_flush_in")]
  public static extern IntPtr new_fuse_flush_in();

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_fuse_flush_in")]
  public static extern void delete_fuse_flush_in(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_read_in_fh")]
  public static extern ulong get_fuse_read_in_fh(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_read_in_offset")]
  public static extern ulong get_fuse_read_in_offset(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_read_in_size")]
  public static extern uint get_fuse_read_in_size(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_read_in_padding")]
  public static extern uint get_fuse_read_in_padding(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_fuse_read_in_copyFrom")]
  public static extern int fuse_read_in_copyFrom(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_fuse_read_in")]
  public static extern IntPtr new_fuse_read_in();

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_fuse_read_in")]
  public static extern void delete_fuse_read_in(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_write_in_fh")]
  public static extern ulong get_fuse_write_in_fh(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_write_in_offset")]
  public static extern ulong get_fuse_write_in_offset(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_write_in_size")]
  public static extern uint get_fuse_write_in_size(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_write_in_write_flags")]
  public static extern uint get_fuse_write_in_write_flags(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_fuse_write_in_copyFrom")]
  public static extern int fuse_write_in_copyFrom(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_fuse_write_in")]
  public static extern IntPtr new_fuse_write_in();

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_fuse_write_in")]
  public static extern void delete_fuse_write_in(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_write_out_size")]
  public static extern void set_fuse_write_out_size(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_write_out_size")]
  public static extern uint get_fuse_write_out_size(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_write_out_padding")]
  public static extern void set_fuse_write_out_padding(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_write_out_padding")]
  public static extern uint get_fuse_write_out_padding(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_fuse_write_out_copyTo")]
  public static extern int fuse_write_out_copyTo(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_fuse_write_out")]
  public static extern IntPtr new_fuse_write_out();

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_fuse_write_out")]
  public static extern void delete_fuse_write_out(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_statfs_out_st")]
  public static extern void set_fuse_statfs_out_st(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_statfs_out_st")]
  public static extern IntPtr get_fuse_statfs_out_st(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_fuse_statfs_out_copyTo")]
  public static extern int fuse_statfs_out_copyTo(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_fuse_statfs_out")]
  public static extern IntPtr new_fuse_statfs_out();

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_fuse_statfs_out")]
  public static extern void delete_fuse_statfs_out(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_fsync_in_fh")]
  public static extern ulong get_fuse_fsync_in_fh(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_fsync_in_fsync_flags")]
  public static extern uint get_fuse_fsync_in_fsync_flags(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_fsync_in_padding")]
  public static extern uint get_fuse_fsync_in_padding(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_fuse_fsync_in_copyFrom")]
  public static extern int fuse_fsync_in_copyFrom(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_fuse_fsync_in")]
  public static extern IntPtr new_fuse_fsync_in();

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_fuse_fsync_in")]
  public static extern void delete_fuse_fsync_in(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_setxattr_in_size")]
  public static extern uint get_fuse_setxattr_in_size(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_setxattr_in_flags")]
  public static extern uint get_fuse_setxattr_in_flags(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_fuse_setxattr_in_copyFrom")]
  public static extern int fuse_setxattr_in_copyFrom(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_fuse_setxattr_in")]
  public static extern IntPtr new_fuse_setxattr_in();

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_fuse_setxattr_in")]
  public static extern void delete_fuse_setxattr_in(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_getxattr_in_size")]
  public static extern uint get_fuse_getxattr_in_size(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_getxattr_in_padding")]
  public static extern uint get_fuse_getxattr_in_padding(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_fuse_getxattr_in_copyFrom")]
  public static extern int fuse_getxattr_in_copyFrom(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_fuse_getxattr_in")]
  public static extern IntPtr new_fuse_getxattr_in();

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_fuse_getxattr_in")]
  public static extern void delete_fuse_getxattr_in(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_getxattr_out_size")]
  public static extern void set_fuse_getxattr_out_size(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_getxattr_out_size")]
  public static extern uint get_fuse_getxattr_out_size(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_getxattr_out_padding")]
  public static extern void set_fuse_getxattr_out_padding(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_getxattr_out_padding")]
  public static extern uint get_fuse_getxattr_out_padding(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_fuse_getxattr_out_copyTo")]
  public static extern int fuse_getxattr_out_copyTo(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_fuse_getxattr_out")]
  public static extern IntPtr new_fuse_getxattr_out();

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_fuse_getxattr_out")]
  public static extern void delete_fuse_getxattr_out(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_init_in_out_major")]
  public static extern void set_fuse_init_in_out_major(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_init_in_out_major")]
  public static extern uint get_fuse_init_in_out_major(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_init_in_out_minor")]
  public static extern void set_fuse_init_in_out_minor(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_init_in_out_minor")]
  public static extern uint get_fuse_init_in_out_minor(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_fuse_init_in_out_copyFrom")]
  public static extern int fuse_init_in_out_copyFrom(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_fuse_init_in_out_copyTo")]
  public static extern int fuse_init_in_out_copyTo(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_fuse_init_in_out")]
  public static extern IntPtr new_fuse_init_in_out();

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_fuse_init_in_out")]
  public static extern void delete_fuse_init_in_out(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_in_header_len")]
  public static extern void set_fuse_in_header_len(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_in_header_len")]
  public static extern uint get_fuse_in_header_len(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_in_header_opcode")]
  public static extern void set_fuse_in_header_opcode(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_in_header_opcode")]
  public static extern uint get_fuse_in_header_opcode(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_in_header_unique")]
  public static extern void set_fuse_in_header_unique(IntPtr jarg1, ulong jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_in_header_unique")]
  public static extern ulong get_fuse_in_header_unique(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_in_header_nodeid")]
  public static extern void set_fuse_in_header_nodeid(IntPtr jarg1, ulong jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_in_header_nodeid")]
  public static extern ulong get_fuse_in_header_nodeid(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_in_header_uid")]
  public static extern void set_fuse_in_header_uid(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_in_header_uid")]
  public static extern uint get_fuse_in_header_uid(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_in_header_gid")]
  public static extern void set_fuse_in_header_gid(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_in_header_gid")]
  public static extern uint get_fuse_in_header_gid(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_in_header_pid")]
  public static extern void set_fuse_in_header_pid(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_in_header_pid")]
  public static extern uint get_fuse_in_header_pid(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_in_header_padding")]
  public static extern void set_fuse_in_header_padding(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_in_header_padding")]
  public static extern uint get_fuse_in_header_padding(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_fuse_in_header_copyFrom")]
  public static extern int fuse_in_header_copyFrom(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_fuse_in_header_structSize")]
  public static extern int fuse_in_header_structSize();

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_fuse_in_header")]
  public static extern IntPtr new_fuse_in_header();

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_fuse_in_header")]
  public static extern void delete_fuse_in_header(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_out_header_len")]
  public static extern void set_fuse_out_header_len(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_out_header_len")]
  public static extern uint get_fuse_out_header_len(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_out_header_error")]
  public static extern void set_fuse_out_header_error(IntPtr jarg1, int jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_out_header_error")]
  public static extern int get_fuse_out_header_error(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_out_header_unique")]
  public static extern void set_fuse_out_header_unique(IntPtr jarg1, ulong jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_out_header_unique")]
  public static extern ulong get_fuse_out_header_unique(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_fuse_out_header_copyTo")]
  public static extern int fuse_out_header_copyTo(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_fuse_out_header")]
  public static extern IntPtr new_fuse_out_header();

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_fuse_out_header")]
  public static extern void delete_fuse_out_header(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_dirent_ino")]
  public static extern void set_fuse_dirent_ino(IntPtr jarg1, ulong jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_dirent_ino")]
  public static extern ulong get_fuse_dirent_ino(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_dirent_off")]
  public static extern void set_fuse_dirent_off(IntPtr jarg1, ulong jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_dirent_off")]
  public static extern ulong get_fuse_dirent_off(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_dirent_namelen")]
  public static extern void set_fuse_dirent_namelen(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_dirent_namelen")]
  public static extern uint get_fuse_dirent_namelen(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_dirent_type")]
  public static extern void set_fuse_dirent_type(IntPtr jarg1, uint jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_dirent_type")]
  public static extern uint get_fuse_dirent_type(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_fuse_dirent_name")]
  public static extern void set_fuse_dirent_name(IntPtr jarg1, string jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_fuse_dirent_name")]
  public static extern string get_fuse_dirent_name(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_fuse_dirent")]
  public static extern IntPtr new_fuse_dirent();

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_fuse_dirent")]
  public static extern void delete_fuse_dirent(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_set_FWBuffer_offset")]
  public static extern void set_FWBuffer_offset(IntPtr jarg1, int jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_FWBuffer_offset")]
  public static extern int get_FWBuffer_offset(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_FWBuffer_initialized")]
  public static extern int get_FWBuffer_initialized(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_FWBuffer_length")]
  public static extern int get_FWBuffer_length(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_FWBuffer_data")]
  public static extern string get_FWBuffer_data(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_FWBuffer")]
  public static extern IntPtr new_FWBuffer(int jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_FWBuffer")]
  public static extern void delete_FWBuffer(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_FWBuffer_Rewind")]
  public static extern void FWBuffer_Rewind(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_FWBuffer_Reset")]
  public static extern void FWBuffer_Reset(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_FWBuffer_EnsureFreeSpace")]
  public static extern int FWBuffer_EnsureFreeSpace(IntPtr jarg1, int jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_FWBuffer_Read__SWIG_0")]
  public static extern int FWBuffer_Read__SWIG_0(IntPtr jarg1, int jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_FWBuffer_Read__SWIG_1")]
  public static extern int FWBuffer_Read__SWIG_1(IntPtr jarg1, int jarg2, uint jarg3, ulong jarg4);

  [DllImport("FuseWrapper", EntryPoint="CSharp_FWBuffer_Write__SWIG_0")]
  public static extern int FWBuffer_Write__SWIG_0(IntPtr jarg1, int jarg2, uint jarg3, ulong jarg4);

  [DllImport("FuseWrapper", EntryPoint="CSharp_FWBuffer_Write__SWIG_1")]
  public static extern int FWBuffer_Write__SWIG_1(IntPtr jarg1, int jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_FWBuffer_GetString")]
  public static extern string FWBuffer_GetString(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_FWBuffer_GetBytes")]
  public static extern int FWBuffer_GetBytes(IntPtr jarg1, string jarg2, int jarg3);

  [DllImport("FuseWrapper", EntryPoint="CSharp_FWBuffer_GetByte")]
  public static extern int FWBuffer_GetByte(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_FWBuffer_AddBytes")]
  public static extern int FWBuffer_AddBytes(IntPtr jarg1, string jarg2, int jarg3);

  [DllImport("FuseWrapper", EntryPoint="CSharp_FWBuffer_AddChar")]
  public static extern int FWBuffer_AddChar(IntPtr jarg1, int jarg2, char jarg3);

  [DllImport("FuseWrapper", EntryPoint="CSharp_FWBuffer_AddString")]
  public static extern int FWBuffer_AddString(IntPtr jarg1, string jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_FWBuffer_AddSubString")]
  public static extern int FWBuffer_AddSubString(IntPtr jarg1, string jarg2, int jarg3, int jarg4);

  [DllImport("FuseWrapper", EntryPoint="CSharp_FWBuffer_AddBuffer")]
  public static extern int FWBuffer_AddBuffer(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_FWBuffer_copyTo")]
  public static extern int FWBuffer_copyTo(IntPtr jarg1, IntPtr jarg2);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_FileBuffer_buf")]
  public static extern IntPtr get_FileBuffer_buf(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_get_FileBuffer_error")]
  public static extern int get_FileBuffer_error(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_new_FileBuffer")]
  public static extern IntPtr new_FileBuffer(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_delete_FileBuffer")]
  public static extern void delete_FileBuffer(IntPtr jarg1);

  [DllImport("FuseWrapper", EntryPoint="CSharp_FileBuffer_addFile")]
  public static extern int FileBuffer_addFile(IntPtr jarg1, string jarg2, ulong jarg3, uint jarg4, ulong jarg5);

  [DllImport("FuseWrapper", EntryPoint="CSharp_FileBuffer_copyTo")]
  public static extern int FileBuffer_copyTo(IntPtr jarg1, IntPtr jarg2);
}
