/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

public class fuse_kstatfs : IDisposable {
  private IntPtr swigCPtr;
  protected bool swigCMemOwn;

  internal fuse_kstatfs(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  internal static IntPtr getCPtr(fuse_kstatfs obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  ~fuse_kstatfs() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      FuseWrapperPINVOKE.delete_fuse_kstatfs(swigCPtr);
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
  }

  public ulong blocks {
    set {
      FuseWrapperPINVOKE.set_fuse_kstatfs_blocks(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_kstatfs_blocks(swigCPtr);
    } 
  }

  public ulong bfree {
    set {
      FuseWrapperPINVOKE.set_fuse_kstatfs_bfree(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_kstatfs_bfree(swigCPtr);
    } 
  }

  public ulong bavail {
    set {
      FuseWrapperPINVOKE.set_fuse_kstatfs_bavail(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_kstatfs_bavail(swigCPtr);
    } 
  }

  public ulong files {
    set {
      FuseWrapperPINVOKE.set_fuse_kstatfs_files(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_kstatfs_files(swigCPtr);
    } 
  }

  public ulong ffree {
    set {
      FuseWrapperPINVOKE.set_fuse_kstatfs_ffree(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_kstatfs_ffree(swigCPtr);
    } 
  }

  public uint bsize {
    set {
      FuseWrapperPINVOKE.set_fuse_kstatfs_bsize(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_kstatfs_bsize(swigCPtr);
    } 
  }

  public uint namelen {
    set {
      FuseWrapperPINVOKE.set_fuse_kstatfs_namelen(swigCPtr, value);
    } 
    get {
      return FuseWrapperPINVOKE.get_fuse_kstatfs_namelen(swigCPtr);
    } 
  }

  public fuse_kstatfs() : this(FuseWrapperPINVOKE.new_fuse_kstatfs(), true) {
  }

}
