/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

public class fuse_setattr_in : IDisposable, BufferReadable {
  private IntPtr swigCPtr;
  protected bool swigCMemOwn;

  internal fuse_setattr_in(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  internal static IntPtr getCPtr(fuse_setattr_in obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  ~fuse_setattr_in() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      FuseWrapperPINVOKE.delete_fuse_setattr_in(swigCPtr);
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
  }

  public uint valid {
    get {
      return FuseWrapperPINVOKE.get_fuse_setattr_in_valid(swigCPtr);
    } 
  }

  public uint padding {
    get {
      return FuseWrapperPINVOKE.get_fuse_setattr_in_padding(swigCPtr);
    } 
  }

  public fuse_attr attr {
    get {
      IntPtr cPtr = FuseWrapperPINVOKE.get_fuse_setattr_in_attr(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new fuse_attr(cPtr, false);
    } 
  }

  public int copyFrom(FWBuffer buf) {
    return FuseWrapperPINVOKE.fuse_setattr_in_copyFrom(swigCPtr, FWBuffer.getCPtr(buf));
  }

  public fuse_setattr_in() : this(FuseWrapperPINVOKE.new_fuse_setattr_in(), true) {
  }

}
