/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

public class fuse_mknod_in : IDisposable, BufferReadable {
  private IntPtr swigCPtr;
  protected bool swigCMemOwn;

  internal fuse_mknod_in(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  internal static IntPtr getCPtr(fuse_mknod_in obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  ~fuse_mknod_in() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      FuseWrapperPINVOKE.delete_fuse_mknod_in(swigCPtr);
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
  }

  public uint mode {
    get {
      return FuseWrapperPINVOKE.get_fuse_mknod_in_mode(swigCPtr);
    } 
  }

  public uint rdev {
    get {
      return FuseWrapperPINVOKE.get_fuse_mknod_in_rdev(swigCPtr);
    } 
  }

  public int copyFrom(FWBuffer buf) {
    return FuseWrapperPINVOKE.fuse_mknod_in_copyFrom(swigCPtr, FWBuffer.getCPtr(buf));
  }

  public fuse_mknod_in() : this(FuseWrapperPINVOKE.new_fuse_mknod_in(), true) {
  }

}
